Repository rackerlabs/support-how-to, pull requests merged in 2020-09, with the labels that each got.

#374 fix broken link
  content/how-to/cloud-servers/configure-mysql-server-on-the-ubuntu-operating-system/index.md
  content/how-to/cloud-servers/install-mysql-server-on-the-ubuntu-operating-system/index.md
  content/how-to/cloud-servers/reset-a-mysql-root-password/index.md
Labels: edit/review: peer

#390 Add the link back with http instead of original https.
  content/how-to/cloud-servers/check-for-a-security-compromise-rescue-mode-investigation/index.md
Labels: edit/review: peer

#391 fix format
  content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2007-and-2010/index.md
Labels: edit/review: peer

#392 add missing article and fix archetype
  archetypes/support-bundle/index.md
  content/how-to/cloud-backup/troubleshoot-cloud-backup-on-linux-servers/index.md
Labels: edit/review: peer

#397 missed edits during migration
  content/how-to/cloud-servers/set-up-mysql-master-slave-replication/index.md
Labels: edit/review: peer

#435 Backup updates per Brett
  content/how-to/cloud-backup/cloud-backup-agent-logging-basics/index.md
  content/how-to/cloud-backup/cloud-backup-faq/index.md
  content/how-to/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows/index.md
  content/how-to/cloud-backup/update-or-install-the-cloud-backup-agent-on-linux/index.md
  content/how-to/cloud-backup/update-the-rackspace-cloud-backup-agent/index.md
Labels: review: peer

#437 Create configure-active-directory-with-integrated-dns
  content/how-to/cloud-servers/configure-active-directory-with-integrated-dns/index.md
Labels: review: peer

#439 database-replication-annual
  content/how-to/cloud-databases/database-replication-with-cloud-databases/index.md
Labels: full audit

#442 databse-timeszones-annual
  content/how-to/cloud-databases/setting-the-time-zone-for-a-cloud-databases-instance/index.md
Labels: full audit

#417 account-switch-feature
  content/how-to/account-management/configure-user-switcher-to-remember-account-logins/index.md
Labels: Ready - On Hold

#445 database-users-annual
  content/how-to/cloud-databases/manage-users-for-cloud-databases/index.md
  content/how-to/cloud-databases/managing-users-for-cloud-databases/index.md
Labels: full audit

#450 database-access-annual
  content/how-to/cloud-databases/public-and-private-access-for-cloud-databases/index.md
Labels: full audit

#447 Create install-the-wsus-server-role
  content/how-to/cloud-servers/install-the-wsus-server-role/index.md
Labels: new

#441 Create limit-ssh-access-by-ip-address
  content/how-to/cloud-servers/limit-ssh-access-by-ip-address/index.md
Labels: new

#440 Create troubleshoot-mssql-job-failures/
  content/how-to/cloud-servers/troubleshoot-mssql-job-failures/index.md
Labels: new

#438 Create review-mssql-server-agent-logs
  content/how-to/cloud-servers/review-mssql-server-agent-logs/index.md
Labels: new

#460 database-grouops-annual
  content/how-to/cloud-databases/manage-cloud-databases-configuration-groups-in-the-cloud-control-panel/index.md
Labels: full audit, review: editor

#443 Create setup-and-use-of-sql-server-management-studio
  content/how-to/set-up-and-use-sql-server-management-studio/index.md
Labels: new, review: peer

#458 slow-query-annual
  content/how-to/cloud-databases/access-slow-query-and-general-logs-for-cloud-databases/index.md
Labels: full audit, review: peer

#453 new nomenclature
  CONTRIBUTING.md
  content/how-to/account-management/combine-invoices-for-rackspace-managed-and-cloud-accounts/index.md
  content/how-to/cloud-databases/cloud-databases-faq/index.md
  content/how-to/cloud-databases/database-replication-with-cloud-databases/index.md
  content/how-to/cloud-databases/high-availability-for-cloud-databases/index.md
  content/how-to/cloud-databases/manage-cloud-databases-ha-groups-in-the-cloud-control-panel/index.md
  content/how-to/cloud-databases/scheduled-backups-for-cloud-databases/index.md
  content/how-to/cloud-dns/cloud-dns-faq/index.md
  content/how-to/cloud-files/best-practices-for-using-cloud-files/index.md
  content/how-to/cloud-images/transfer-images-between-regions-of-the-rackspace-open-cloud/index.md
  content/how-to/cloud-networks/set-up-apache2-web-server-on-two-instances-with-shared-ip/index.md
  content/how-to/cloud-orchestration/how-to-scale-multinode-wordpress-by-using-rackspace-orchestration/index.md
  content/how-to/cloud-orchestration/use-rackspace-orchestration-to-build-a-wordpress-stack/index.md
  content/how-to/cloud-servers/about-cloud-server-images/index.md
  content/how-to/cloud-servers/cloud-to-cloud-migration/index.md
  content/how-to/cloud-servers/configure-mysql-source-replica-replication/index.md
  content/how-to/cloud-servers/configure-mysql-source-source-replication/index.md
  content/how-to/cloud-servers/getting-started-with-apache-hadoop-on-rackspace-cloud/index.md
  content/how-to/cloud-servers/high-performance-computing-cluster-in-a-cloud-environment/index.md
  content/how-to/cloud-servers/launch-a-windows-web-farm-with-web-deploy/index.md
  content/how-to/cloud-servers/migrating-to-a-general-purpose-or-io-server/index.md
  content/how-to/cloud-servers/mysql-replication-masterslave/index.md
  content/how-to/cloud-servers/nova-agent-unix-and-rackspace-agent-windows/index.md
  content/how-to/cloud-servers/set-up-apache-virtual-hosts-on-the-ubuntu-operating-system/index.md
  content/how-to/cloud-servers/set-up-mysql-primary-replica-replication/index.md
  content/how-to/cloud-servers/set-up-mysql-source-replica-replication/index.md
  content/how-to/cloud-servers/using-cloud-servers-tags/index.md
  content/how-to/general/dns-fundamentals/index.md
  content/how-to/rackspace-auto-scale/rackspace-auto-scale-control-panel-user-guide-concepts/index.md
  content/how-to/retired-articles/add-another-wordpress-site-to-an-existing-cloud-orchestration-stack/index.md
  content/how-to/retired-articles/cloud-native-security/index.md
  content/how-to/retired-articles/cloud-servers-with-managed-operations-support-for-linux/index.md
  content/how-to/retired-articles/managed-dns-faq/index.md
  content/how-to/retired-articles/object-storage-swift-in-a-rack-with-amds-seamicro-sm15000/index.md
  content/how-to/retired-articles/test-and-send-mail-using-php/index.md
  content/how-to/rpc-openstack/apache-hadoop-on-rackspace-private-cloud/index.md
  static/_redirects
Labels: review: peer

#448 Create force-password-change-upon-next-login/
  content/how-to/cloud-servers/force-a-password-change-on-the-next-login/index.md
Labels: new, review: peer

#454 Create use-systemctl-to-manage-services
  content/how-to/cloud-servers/use-systemctl-to-manage-services/index.md
Labels: new

#467 full-audit-autoscale-faq
  content/how-to/rackspace-auto-scale/rackspace-auto-scale-faq/index.md
Labels: full audit, review: peer

#469 full-audit-autoscale-concepts
  content/how-to/rackspace-auto-scale/rackspace-auto-scale-control-panel-user-guide-concepts/index.md
Labels: full audit, review: peer

#455 Create schedule-reboots-in-ubuntu/
  content/how-to/cloud-servers/schedule-reboots-in-the-ubuntu-operating-system/index.md
Labels: new

#465 Minor changes
  content/how-to/cloud-servers/install-python-novaclient-on-windows/index.md
Labels: review: peer

#475 Minor Style changes
  content/how-to/cloud-servers/installing-fwbuilder/index.md
Labels: review: editor

#470 full-audit-autoscale-group
  content/how-to/rackspace-auto-scale/rackspace-auto-scale-control-panel-user-guide-create-a-scaling-group/index.md
Labels: full audit, review: peer

#474 full-audit-autoscale-guide
  content/how-to/rackspace-auto-scale/rackspace-auto-scale-control-panel-user-guide-introduction/index.md
Labels: full audit, review: editor

#472 full-audit-autoscale-policy
  content/how-to/rackspace-auto-scale/rackspace-auto-scale-control-panel-user-guide-create-a-scaling-policy/index.md
Labels: full audit, review: editor

#457 Create disable-maintenance-mode-in-magento
  content/how-to/cloud-servers/disable-maintenance-mode-in-magento/index.md
Labels: new

#476 Retirement Candidate and structural edits
  content/how-to/cloud-servers/testing-network-services-with-netcat/index.md
Labels: full audit, review: peer

#477 full-audit-autoscale-glossary
  content/how-to/rackspace-auto-scale/rackspace-auto-scale-glossary/index.md
Labels: full audit, review: peer

#478 full-audit-autoscale-overview
  content/how-to/rackspace-auto-scale/rackspace-auto-scale-overview/index.md
Labels: full audit, review: peer

#479 full-audit-autoscale-cooldowns
  content/how-to/rackspace-auto-scale/how-auto-scale-cooldowns-work/index.md
Labels: full audit, review: peer

#480 full-audit-autoscale-tips
  content/how-to/rackspace-auto-scale/rackspace-auto-scale-tips-and-how-tos/index.md
Labels: full audit, review: peer

#487 restore article missed in migration
  content/how-to/rackspace-email/set-up-multifactor-authentification-applications-for-cloud-office/index.md
Labels: review: peer

#489 Cloud networks interface
  content/how-to/cloud-servers/add-a-cloud-network-interface-to-a-cloud-server/index.md
Labels: review: peer
