Repository rackerlabs/support-how-to, pull requests merged in 2020-10, with the labels that each got.

#491 On metal
  content/how-to/cloud-servers/onmetal-cloud-server-overview/index.md
  content/how-to/cloud-servers/what-is-new-with-onmetal-cloud-servers/index.md
Labels: review: peer

#466 Create configuring-ip-security-in-iis
  content/how-to/cloud-servers/configuring-ip-security-in-iis/index.md
Labels: new

#484 full-audit-autoscale-webhooks
  content/how-to/rackspace-auto-scale/configure-rackspace-auto-scale-web-hooks-with-rackspace-monitoring/index.md
Labels: full audit, review: peer

#483 Minor changes in style and structure
  content/how-to/cloud-servers/prepare-to-migrate-a-linux-server/index.html
  content/how-to/cloud-servers/prepare-to-migrate-a-linux-server/index.md
Labels: review: peer

#502 Iredmail retired article
  content/how-to/retired-articles/ubuntu-904-iredmail-installation/index.md
  static/_redirects
Labels: retired, review: peer

#504 Standard and general purpose servers
  content/how-to/cloud-servers/resize-standard-and-general-purpose-servers/index.html
  content/how-to/cloud-servers/resize-standard-and-general-purpose-servers/index.md
Labels: review: peer

#482 full-audit-autoscale-f5
  content/how-to/rackspace-auto-scale/cloud-bursting-using-auto-scale-rackconnect-and-f5-load-balancers/index.md
Labels: full audit, review: peer

#496 full-audit-clb-health
  content/how-to/cloud-load-balancers/configure-a-health-monitor-in-cloud-load-balancers/index.md
Labels: full audit, review: peer

#486 full-audit-clb-caching
  content/how-to/cloud-load-balancers/content-caching-for-cloud-load-balancers/index.md
Labels: full audit, review: peer

#495 Changes in style
  content/how-to/cloud-servers/prepare-to-migrate-a-linux-server/index.md
Labels: review: peer

#498 full-audit-clb-draining
  content/how-to/cloud-load-balancers/drain-connections-to-load-balanced-server/index.md
  content/how-to/cloud-load-balancers/draining-a-load-balanced-server/index.md
Labels: full audit, review: peer

#508 full-audit-clb-domains
  content/how-to/cloud-load-balancers/point-domains-to-load-balancers/index.md
  content/how-to/cloud-load-balancers/pointing-domains-to-load-balancers/index.md
Labels: full audit, review: peer

#510 full-audit-clb-algorithms
  content/how-to/cloud-load-balancers/cloud-load-balancer-scheduling-algorithms/index.md
Labels: full audit, review: peer

#511 retire-clb-ord-region
  content/how-to/retired-articles/cloud-load-balancers-ord-region-migration-faq/index.md
  static/_redirects
Labels: retired, review: peer

#512 Serve your domain
  content/how-to/cloud-servers/serve-your-domain-from-a-rackspace-cloud-server/index.md
  content/how-to/cloud-servers/serving-your-domain-from-a-rackspace-cloud-server/index.md
  static/_redirects
Labels: review: peer

#506 full-audit-clb-network
  content/how-to/cloud-load-balancers/use-rackspace-network-effectively/ServerDetails.png
  content/how-to/cloud-load-balancers/use-rackspace-network-effectively/index.md
  content/how-to/cloud-load-balancers/using-the-rackspace-network-effectively/index.md
Labels: full audit

#497 full-audit-clb-overload
  content/how-to/cloud-load-balancers/prevent-server-overload-with-cloud-load-balancers/index.md
Labels: full audit, review: peer

#509 full-audit-clb-protocols
  content/how-to/cloud-load-balancers/available-protocols-when-configuring-a-cloud-load-balancer/index.md
Labels: full audit, review: peer

#518 update move date
  content/how-to/general/lon7-global-switch-data-center-migration-faq-for-managed-customers/index.md
Labels: review: peer

#520 sjc2 faq
  content/how-to/general/sjc2-data-center-relocation-managed-customer-faq/index.md
Labels: review: peer

#522 replacing images
  content/how-to/cloud-load-balancers/load-balancing-internal-ips-in-the-same-region/IPs.png
  content/how-to/cloud-load-balancers/load-balancing-internal-ips-in-the-same-region/clb-create.png
  content/how-to/cloud-load-balancers/load-balancing-internal-ips-in-the-same-region/index.md
Labels: full audit

#513 Configure flash drives
  content/how-to/cloud-servers/configure-flash-drives-in-high-io-instances-as-data-drives/index.md
Labels: review: peer

#545 Check system load
  content/how-to/cloud-servers/check-the-system-load-on-linux/index.md
  content/how-to/cloud-servers/checking-system-load-on-linux/index.md
  static/_redirects
Labels: review: peer

#543 Create anyconnect-version-update
  content/how-to/cloud-servers/update-your-anyconnect-version-in-the-rackspace-portal/index.md
Labels: new, review: peer

#558 Redirects article to match permalink, changes in style
  content/how-to/cloud-servers/upgrade-resources-for-general-purpose-or-io-optimized-cloud-servers/index.md
  content/how-to/cloud-servers/upgrading-resources-for-general-purpose-or-io-optimized-cloud-servers/index.md
  static/_redirects
Labels: review: peer

#565 Changes permalink to match title, changes in structure and style
  content/how-to/cloud-servers/add-a-linux-user-with-document-root-permissions/index.md
  content/how-to/cloud-servers/how-to-add-linux-user-with-document-root-permissions/index.md
  static/_redirects
Labels: review: peer

#559 Create shutdown-server-from-the-cloud-portal
  content/how-to/cloud-servers/shut-down-a-server-from-the-cloud-portal/index.md
Labels: new

#542 Create response-codes
  content/how-to/cloud-servers/http-response-status-codes/index.md
Labels: new

#514 Rse webmail new
  content/how-to/rackspace-email/administrator-guide-for-rackspace-webmail-multi-factor-authentication/admin-only-settings.png
  content/how-to/rackspace-email/administrator-guide-for-rackspace-webmail-multi-factor-authentication/index.md
  content/how-to/rackspace-email/administrator-guide-for-rackspace-webmail-multi-factor-authentication/reset-mfa.png
  content/how-to/rackspace-email/manage-multi-factor-authentication-for-rackspace-webmail/index.md
  content/how-to/rackspace-email/manage-multi-factor-authentication-for-rackspace-webmail/mfa-settings.png
  content/how-to/rackspace-email/manage-multi-factor-authentication-for-rackspace-webmail/mfa-trusted-devices.png
  content/how-to/rackspace-email/manage-multi-factor-authentication-for-rackspace-webmail/reset-mfa.png
Labels: new

#552 full-audit-tcpdump
  content/how-to/cloud-servers/capture-packets-with-tcpdump/index.md
  content/how-to/cloud-servers/capturing-packets-with-tcpdump/index.md
Labels: full audit

#567 Cbs maint updates
  content/how-to/cloud-block-storage/minimizing-the-impact-of-cloud-block-storage-maintenance/index.md
Labels: enhancement

#560 Create configuring-log-shipping-for-mssql-server
  content/how-to/cloud-servers/configure-log-shipping-for-mssql-server/index.md
Labels: new, review: peer

#568 full-audit-cbu-information
  content/how-to/cloud-backup/rackspace-cloud-backup-view-backup-information/index.md
Labels: full audit, review: peer

#569 full-audit-cbu-trobleshooting
  content/how-to/cloud-backup/cloud-backup-troubleshooting/index.md
Labels: full audit, review: peer

#570 full-audit-cbu-maintenance
  content/how-to/cloud-backup/create-a-maintenance-backup-plan-in-sql-server-2008-r2-using-the-wizard/index.md
Labels: full audit, review: peer

#571 full-audit-cbu-preferences
  content/how-to/cloud-backup/rackspace-cloud-backup-preferences/index.md
Labels: full audit, review: peer

#598 full-audit-cb-agent-silent
  content/how-to/cloud-backup/rackspace-cloud-backup-install-the-agent-on-windows-by-using-silent-installation/index.md
Labels: full audit, review: peer

#587 full-audit-cb-databases
  content/how-to/cloud-backup/rackspace-cloud-backup-backing-up-databases/index.md
Labels: full audit, review: peer

#604 Updates audit and last modified dates
  content/how-to/cloud-servers/terms-of-service/index.md
Labels: review: peer

#602 Create ssh-public-key-authentication
  content/how-to/cloud-servers/enable-ssh-public-key-authentication/index.md
Labels: new, review: peer

#612 full-audit-citrix
  content/how-to/cloud-servers/upgrade-citrix-xen-server-tools-for-windows-cloud-servers/index.md
  content/how-to/cloud-servers/upgrade-citrix-xenserver-tools-for-windows-cloud-servers/index.md
Labels: full audit, review: peer

#610 full-audit-rbac
  content/how-to/cloud-servers/permissions-matrix-for-role-based-access-control-rbac/index.md
Labels: full audit, review: peer

#609 Create password-change-logs-in-linux
  content/how-to/cloud-servers/view-password-change-logs-in-linux/index.md
Labels: new, review: peer

#607 full-audit-2fa-google
  content/how-to/cloud-servers/set-up-two-factor-authentication-by-using-google-authenticator/index.md
Labels: full audit, review: peer

#582 SME feedback and edits for full audits
  content/how-to/cloud-servers/installing-ftp-on-windows-server-2012-r2/index.md
  content/how-to/cloud-servers/log-in-to-your-server-via-rdp-windows/index.md
Labels: full audit

#608 Create troubleshooting-windows-high-cpu-usage
  content/how-to/cloud-servers/troubleshoot-windows-high-cpu-usage/index.md
Labels: new

#614 Create viewing-email-headers.md
  content/how-to/rackspace-email/view-email-headers/full_header_rs.png
  content/how-to/rackspace-email/view-email-headers/header_window_hex.png
  content/how-to/rackspace-email/view-email-headers/inbox_preview_hex.png
  content/how-to/rackspace-email/view-email-headers/index.md
  content/how-to/rackspace-email/view-email-headers/view_full_header_rs.png
  content/how-to/rackspace-email/view-email-headers/view_message_details_hex.png
Labels: new, review: peer

#615 Full audit python iis7
  content/how-to/cloud-servers/set-up-python-on-iis-75/index.md
Labels: full audit, review: peer

#617 Full audit multiauthentication
  content/how-to/cloud-servers/multi-factor-authentication-from-the-cloud-control-panel/index.md
  content/how-to/cloud-servers/multi-factor-authentication-from-the-myrackspace-portal/index.md
  content/how-to/rackspace-email/view-email-headers/index.md
Labels: full audit
