Repository rackerlabs/support-how-to, pull requests merged in 2020-11, with the labels that each got.

#623 New article
  content/how-to/rackspace-email/manage-cloud-office-administrator-information-in-the-control-panel/index.md
Labels: new

#622 Create how-to-drop-tables-in-mysql
  content/how-to/cloud-servers/drop-tables-in-mysql/index.md
Labels: new

#624 audit-retire-sockets
  content/how-to/retired-articles/install-nginx-and-php-fpm-running-on-unix-file-sockets/index.md
  static/_redirects
Labels: retired, review: peer

#629 retire windows server 2012
  content/how-to/retired-articles/windows-server-2012-r2-with-managed-operations-support/index.md
  static/_redirects
Labels: full audit, review: editor

#633 retire exchange mo server
  content/how-to/retired-articles/manually-configure-outlook-2011-for-email-hosted-on-exchange-2013/01_0.png
  content/how-to/retired-articles/manually-configure-outlook-2011-for-email-hosted-on-exchange-2013/1_53.png
  content/how-to/retired-articles/manually-configure-outlook-2011-for-email-hosted-on-exchange-2013/2_50.png
  content/how-to/retired-articles/manually-configure-outlook-2011-for-email-hosted-on-exchange-2013/3_47.png
  content/how-to/retired-articles/manually-configure-outlook-2011-for-email-hosted-on-exchange-2013/amber.png
  content/how-to/retired-articles/manually-configure-outlook-2011-for-email-hosted-on-exchange-2013/green.png
  content/how-to/retired-articles/manually-configure-outlook-2011-for-email-hosted-on-exchange-2013/index.md
  static/_redirects
Labels: retired, review: peer

#634 fix-mo-redirect
  static/_redirects
Labels: review: peer

#638 full-audit-ios
  content/how-to/exchange/use-simple-email-setup-to-configure-ios-devices-for-email-hosted-on-exchange-2010/index.md
Labels: full audit, review: peer

#637 full-audit-2007-2010
  content/how-to/exchange/manually-configure-outlook-2007-for-email-hosted-on-exchange-2010/index.md
Labels: full audit, review: peer

#635 full-audit-android-exchange2010
  content/how-to/exchange/manually-configure-android-devices-for-email-hosted-on-exchange-2010/index.md
Labels: full audit, review: peer

#628 full audit logrotate
  content/how-to/cloud-servers/sample-logrotate-configuration-and-troubleshooting/index.md
Labels: full audit, review: peer

#625 full-audit-faq
  content/how-to/cloud-servers/cloud-servers-faq/index.md
Labels: full audit, review: peer

#626 full audit iptables
  content/how-to/cloud-servers/introduction-to-iptables/index.md
Labels: full audit, review: peer

#640 Pr/viridaria/639
  content/how-to/retired-articles/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2013/0000.png
  content/how-to/retired-articles/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2013/image001_2_0.png
  content/how-to/retired-articles/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2013/image002_2.png
  content/how-to/retired-articles/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2013/image003_2.png
  content/how-to/retired-articles/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2013/image004_2.png
  content/how-to/retired-articles/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2013/image005_2.png
  content/how-to/retired-articles/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2013/image006_2.png
  content/how-to/retired-articles/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2013/image007_2.png
  content/how-to/retired-articles/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2013/index.md
  static/_redirects
Labels: retired, review: peer

#641 Full audit exchange mobile
  content/how-to/exchange/configure-email-clients-and-mobile-devices-for-email-hosted-on-exchange/index.md
Labels: full audit, review: peer

#643 cve2020-1472
  content/how-to/dedicated-hosting/remediation-of-cve-2020-1472-netlogon-elevation-of-privilege-vulnerability/index.md
Labels: new, review: editor

#642 Full audit exchange contact
  content/how-to/exchange/add-a-microsoft-exchange-contact/index.md
  content/how-to/exchange/adding-a-microsoft-exchange-contact/index.md
Labels: full audit, review: editor

#647 sjc2 relo
  content/how-to/general/sjc2-data-center-relocation-colocation-customer-faq/index.md
  content/how-to/general/sjc2-data-center-relocation/index.md
  static/_redirects
Labels: review: peer

#657 retire entourage
  content/how-to/retired-articles/manually-configure-entourage-for-email-hosted-on-exchange-2010/EAEntourage2008EWSExchange.png
  content/how-to/retired-articles/manually-configure-entourage-for-email-hosted-on-exchange-2010/EAEntourage2008EWSExchange2.png
  content/how-to/retired-articles/manually-configure-entourage-for-email-hosted-on-exchange-2010/Exchange2010Entourage.png
  content/how-to/retired-articles/manually-configure-entourage-for-email-hosted-on-exchange-2010/Exchange2010Entourage2.png
  content/how-to/retired-articles/manually-configure-entourage-for-email-hosted-on-exchange-2010/index.md
  static/_redirects
Labels: retired, review: peer

#652 Create where-to-put-documentroot-in-centos
  content/how-to/cloud-servers/where-to-put-documentroot-in-centos/index.md
Labels: new, review: peer

#661 full-audit-public-folders
  content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2007-and-2010/index.md
  content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2010/Basic_a.png
  content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2010/Create_a.png
  content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2010/bulkdelete2.png
  content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2010/childsubfolder.png
  content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2010/delete_a.png
  content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2010/index.md
  content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2010/rename_a.png
  content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2010/search.png
  content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2010/subfolders2_a.png
  content/how-to/exchange/public-folder-permissions-for-exchange-2007-and-2010/index.md
Labels: full audit, review: peer

#660 full-audit-directory-sync
  content/how-to/exchange/rackspace-directory-sync-best-practices-and-common-errors/index.md
Labels: full audit, review: peer

#655 Create php-memory-limit
  content/how-to/cloud-servers/php-memory-limit/index.md
Labels: new, review: peer

#662 full-edit-hosted-exchange
  content/how-to/exchange/terminal-services-in-a-hosted-exchange-environment/index.md
Labels: full audit, review: peer

#659 Create determine-dfsr-staging-quota
  content/how-to/cloud-servers/determine-dfsr-staging-quota/index.md
Labels: new, review: peer

#670 Create configure-active-directory-performance-monitoring
  content/how-to/configure-active-directory-performance-monitoring/index.md
Labels: new, review: peer

#673 full-audit-x-calendar
  content/how-to/exchange/share-a-microsoft-exchange-2010-calendar-using-outlook-2010/index.md
Labels: full audit, review: peer

#669 Create troubleshooting-dfs-replication
  content/how-to/cloud-servers/troubleshooting-dfs-replication/index.md
Labels: new, review: peer

#658 Create log-off-existing-sessions-in-linux
  content/how-to/cloud-servers/log-off-existing-sessions-in-linux/index.md
Labels: new, review: peer

#675 full-audit-monitoring-about
  content/how-to/rackspace-monitoring/about-the-rackspace-monitoring-agent/index.md
Labels: full audit, review: peer

#656 Create what-is-a-500-internal-server-error/
  content/how-to/cloud-servers/what-is-a-500-internal-server-error/index.md
Labels: new, review: peer

#676 full-audit-x-transferdomain
  content/how-to/exchange/transfer-a-domains-email-services-to-another-account/index.md
Labels: full audit, review: peer

#678 full-audit-credmgr
  content/how-to/exchange/clear-credential-manager/index.md
Labels: full audit, review: peer

#677 full-audit-x-sync
  content/how-to/exchange/rackspace-directory-sync-operation-guide/index.md
Labels: full audit, review: peer

#674 full-audit-x-windowsphone
  content/how-to/exchange/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2010/0000.png
  content/how-to/exchange/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2010/image001_2.png
  content/how-to/exchange/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2010/image002_2.png
  content/how-to/exchange/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2010/image003_2.png
  content/how-to/exchange/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2010/image004_2.png
  content/how-to/exchange/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2010/image005_2.png
  content/how-to/exchange/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2010/image006_2.png
  content/how-to/exchange/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2010/image007_2.png
  content/how-to/exchange/manually-configure-windows-phone-devices-for-email-hosted-on-exchange-2010/index.md
Labels: full audit, review: peer

#679 full-audit-mon-language
  content/how-to/rackspace-monitoring/alarm-language-in-rackspace-monitoring/index.md
Labels: full audit, review: peer

#681 full-audit-mon-instandconfig
  content/how-to/rackspace-monitoring/install-and-configure-the-rackspace-monitoring-agent/index.md
Labels: full audit, review: peer

#590 update instructions for CBUI changes - merge Dec or Jan
  content/how-to/account-management/combine-invoices-for-rackspace-managed-and-cloud-accounts/index.md
Labels: blocked

#680 full-audit-mon-cli
  content/how-to/rackspace-monitoring/getting-started-with-rackspace-monitoring-cli/index.md
Labels: full audit, review: peer

#682 full-audit-mon-mobile
  content/how-to/rackspace-monitoring/introducing-rackspace-monitoring-on-mobile-devices/index.md
Labels: full audit, review: peer

#684 full-audit-mon-mobilealerts
  content/how-to/rackspace-monitoring/mobile-alerts-from-rackspace-monitoring/index.md
Labels: full audit, review: peer

#683 full-audit-mon-health
  content/how-to/rackspace-monitoring/introduction-to-agent-health-monitoring/index.md
Labels: full audit, review: peer

#685 full-audit-mon-users
  content/how-to/rackspace-monitoring/monitoring-differences-between-rackspace-server-users-and-non-rackspace-server-users/index.md
Labels: full audit, review: peer

#686 full-audit-mon-pillars
  content/how-to/rackspace-monitoring/pillars-of-the-rackspace-monitoring-solution/index.md
Labels: full audit, review: peer

#688 full-audit-mon-chef
  content/how-to/rackspace-monitoring/rackspace-monitoring-automation-integrate-monitoring-with-chef/index.md
Labels: full audit, review: peer

#689 full-audit-mon-resources
  content/how-to/rackspace-monitoring/rackspace-monitoring-how-tos-and-other-resources/index.md
Labels: full audit, review: peer
