Repository rackerlabs/support-how-to, pull requests merged in 2020-12, with the labels that each got.

#690 additions per Sarah W.
  content/how-to/general/sjc2-data-center-relocation/index.md
Labels: review: peer

#697 retire-x-imap
  content/how-to/retired-articles/imappop-to-exchange/1.png
  content/how-to/retired-articles/imappop-to-exchange/10.png
  content/how-to/retired-articles/imappop-to-exchange/5.png
  content/how-to/retired-articles/imappop-to-exchange/6.png
  content/how-to/retired-articles/imappop-to-exchange/7.png
  content/how-to/retired-articles/imappop-to-exchange/index.md
  content/how-to/retired-articles/imappop-to-exchange/three.png
Labels: retired, review: peer

#695 full-audit-mon-troubleshooting
  content/how-to/rackspace-monitoring/troubleshooting-the-rackspace-monitoring-agent/index.md
Labels: full audit, review: peer

#694 full-audit-mon-matrix
  content/how-to/rackspace-monitoring/rackspace-monitoring-support-matrix/index.md
Labels: full audit, review: peer

#696 full-audit-x-faq
  content/how-to/exchange/exchange-faq/index.md
Labels: full audit

#704 full-audit-x-ios-2013
  content/how-to/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2013/1.PNG
  content/how-to/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2013/10.png
  content/how-to/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2013/2.PNG
  content/how-to/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2013/3.PNG
  content/how-to/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2013/4.PNG
  content/how-to/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2013/5.PNG
  content/how-to/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2013/6.PNG
  content/how-to/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2013/7.PNG
  content/how-to/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2013/8.PNG
  content/how-to/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2013/9.png
  content/how-to/exchange/manually-configure-ios-devices-for-email-hosted-on-exchange-2013/index.md
Labels: full audit, review: peer

#705 full-audit-dns-change
  content/how-to/rackspace-cdn/change-dns-to-enable-rackspace-cdn/index.md
Labels: full audit, review: peer

#706 full-audit-cdn-log
  content/how-to/rackspace-cdn/enable-log-delivery-in-rackspace-cdn/index.md
Labels: full audit, review: peer

#712 full-audit-cdn-terminology
  content/how-to/rackspace-cdn/rackspace-cdn-terminology/index.md
Labels: full audit, review: peer

#711 full-audit-cdn-overview
  content/how-to/rackspace-cdn/rackspace-cdn-overview/index.md
Labels: full audit, review: peer

#710 full-audit-cdn-cached
  content/how-to/rackspace-cdn/rackspace-cdn-object-is-not-being-cached/index.md
Labels: full audit, review: peer

#709 full-audit-cdn-disablelog
  content/how-to/rackspace-cdn/enable-or-disable-logging-in-rackspace-cdn/index.md
Labels: full audit, review: peer

#714 full-audit-cdn-rename
  content/how-to/rackspace-cdn/rename-a-rackspace-cdn-service/index.md
Labels: full audit, review: editor

#715 edits
  content/how-to/rackspace-cdn/uses-of-rackspace-cdn/index.md
Labels: full audit, review: editor

#713 Add Dependabot automated security update bot
  .github/dependabot.yml
Labels: security

#722 full-audit-cdn-what
  content/how-to/rackspace-cdn/what-is-a-cdn/index.md
Labels: full audit, review: editor

#725 full-audit-x-publicfolders
  content/how-to/retired-articles/microsoft-exchange-public-folders/microsoft-exchange-public-folders.md
  static/_redirects
Labels: retired, review: peer

#726 retire old DC migration faqs
  content/how-to/retired-articles/dfw1-data-center-migration-customer-faq/index.md
  content/how-to/retired-articles/hkg1-data-center-migration-customer-faq/index.md
  content/how-to/retired-articles/hkg2-data-center-migration-customer-faq/index.md
  content/how-to/retired-articles/iad2-data-center-migration-customer-faq/index.md
  content/how-to/retired-articles/ord1-cr5-cr8-data-center-consolidation-faq/index.md
  content/how-to/retired-articles/ord1-data-center-consolidation-faq/index.md
  static/_redirects
Labels: review: peer

#729 full-audit-x-directoryadmins
  content/how-to/exchange/rackspace-directory-sync-administrators-guide/index.md
Labels: full audit, review: peer

#727 full-audit-x-multiple
  content/how-to/exchange/add-multiple-contacts-to-exchange/cp-contacts.jpg
  content/how-to/exchange/add-multiple-contacts-to-exchange/index.md
  content/how-to/exchange/add-multiple-contacts-to-exchange/microsoft-exchange-contacts-link.png
Labels: full audit, review: peer

#733 additional ip
  content/how-to/cloud-networks/requesting-additional-ipv4-addresses-for-cloud-servers/index.md
Labels: review: peer

#735 retire-bb-exchange
  content/how-to/retired-articles/manually-configure-blackberry-10-devices-for-email-hosted-on-exchange-2013/1_25_0.png
  content/how-to/retired-articles/manually-configure-blackberry-10-devices-for-email-hosted-on-exchange-2013/2_22_0.png
  content/how-to/retired-articles/manually-configure-blackberry-10-devices-for-email-hosted-on-exchange-2013/3_20_0.png
  content/how-to/retired-articles/manually-configure-blackberry-10-devices-for-email-hosted-on-exchange-2013/4_13_0.png
  content/how-to/retired-articles/manually-configure-blackberry-10-devices-for-email-hosted-on-exchange-2013/5_13_0.png
  content/how-to/retired-articles/manually-configure-blackberry-10-devices-for-email-hosted-on-exchange-2013/6_14_0.png
  content/how-to/retired-articles/manually-configure-blackberry-10-devices-for-email-hosted-on-exchange-2013/7_7_0.png
  content/how-to/retired-articles/manually-configure-blackberry-10-devices-for-email-hosted-on-exchange-2013/8_5_0.png
  content/how-to/retired-articles/manually-configure-blackberry-10-devices-for-email-hosted-on-exchange-2013/9_4_0.png
  content/how-to/retired-articles/manually-configure-blackberry-10-devices-for-email-hosted-on-exchange-2013/index.md
  static/_redirects
Labels: retired, review: peer

#740 updates to steps and procedures
  CONTRIBUTING.md
Labels: review: peer

#745 retire exchange 2010
  content/how-to/retired-articles/set-up-your-outlook-email-client-on-exchange-2010-via-the-outlook-web-app/2133.1b.png
  content/how-to/retired-articles/set-up-your-outlook-email-client-on-exchange-2010-via-the-outlook-web-app/2133.2a_1.png
  content/how-to/retired-articles/set-up-your-outlook-email-client-on-exchange-2010-via-the-outlook-web-app/2133.3a.png
  content/how-to/retired-articles/set-up-your-outlook-email-client-on-exchange-2010-via-the-outlook-web-app/2133.4a.png
  content/how-to/retired-articles/set-up-your-outlook-email-client-on-exchange-2010-via-the-outlook-web-app/2133.5b.png
  content/how-to/retired-articles/set-up-your-outlook-email-client-on-exchange-2010-via-the-outlook-web-app/2133.6a.png
  content/how-to/retired-articles/set-up-your-outlook-email-client-on-exchange-2010-via-the-outlook-web-app/index.md
  static/_redirects
Labels: retired, review: peer

#746 removing exchange 2007 references
  content/how-to/exchange/public-folders-availability-for-hosted-exchange-2013/index.md
Labels: full audit, review: editor

#752 retire-migrating-public-folder
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_export_pic1.png
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_export_pic2.png
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_export_pic3.png
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_export_pic4png.jpg
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_export_pic5png.png
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_export_pic6png.png
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_import_pic10_0.jpg
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_import_pic11.jpg
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_import_pic12.jpg
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_import_pic13.jpg
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_import_pic7png.png
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_import_pic8png.jpg
  content/how-to/retired-articles/migrating-public-folder-data/Outlook_2010_-_import_pic9.png
  content/how-to/retired-articles/migrating-public-folder-data/index.md
  static/_redirects
Labels: retired, review: peer

#758 full-audit-o11e10
  content/how-to/exchange/manually-configure-outlook-2011-for-email-hosted-on-exchange-2010/index.md
Labels: full audit, review: editor

#760 some quick corrections and wrap
  content/how-to/exchange/manually-configure-mac-mail-for-email-hosted-on-exchange-2010/index.md
Labels: full audit, review: editor

#753 Create new article about live migrations
  content/how-to/cloud-servers/migrations-in-rackspace-cloud/index.md
Labels: new

#761 arranged images, added two new ones, checked general structure
  content/how-to/exchange/manage-distribution-lists-in-exchange/DL11.png
  content/how-to/exchange/manage-distribution-lists-in-exchange/DL6.png
  content/how-to/exchange/manage-distribution-lists-in-exchange/DL7.png
  content/how-to/exchange/manage-distribution-lists-in-exchange/dl1.png
  content/how-to/exchange/manage-distribution-lists-in-exchange/index.md
  content/how-to/exchange/manage-distribution-lists-in-exchange/list1.jpg
  content/how-to/exchange/manage-distribution-lists-in-exchange/list2.jpg
  content/how-to/exchange/manage-distribution-lists-in-exchange/list3.png
  content/how-to/exchange/manage-distribution-lists-in-exchange/list4.png
  content/how-to/exchange/manage-distribution-lists-in-exchange/list5.png
Labels: full audit, review: peer
