Repository rackerlabs/support-how-to, pull requests merged in 2021-03, with the labels that each got.

#903 audit-intel-checks
  content/how-to/rackspace-intelligence/working-with-alarms-checks-entities-notifications-and-notification-plans-in-rackspace/index.md
Labels: full audit, review: peer

#904 audit-intel-vocabulary
  content/how-to/rackspace-intelligence/learning-the-rackspace-intelligence-vocabulary/index.md
Labels: full audit, review: peer

#905 audit-intel-plans
  content/how-to/rackspace-intelligence/working-with-rackspace-intelligence-notification-plans/index.md
Labels: full audit, review: peer

#907 retire-email-recovery
  content/how-to/rackspace-email/add-self-service-password-recovery-to-your-rackspace-email-webmail-site/index.md
  static/_redirects
Labels: retired, review: peer

#909 Create mysql-java-database-connectivity-communications-exception
  mysql-java-database-connectivity-communications-exception/index.md
Labels: new, review: peer

#908 Create restrict-ssh-login-to-a-specific-ip-or-host
  content/how-to/cloud-servers/restrict-ssh-login-to-a-specific-ip-or-host/index.md
Labels: new, review: peer

#906 New article - Monitoring system authentication
  content/how-to/cloud-servers/how-to-monitor-system-authentication-logs-in-ubuntu/index.md
Labels: new, review: peer

#913 Create creating-a-dns-server
  content/how-to/create-a-dns-server/index.md
Labels: new, review: sme or author

#932 Create basic-types-of-linux-users-and-how-to-check-them - ccl version
  content/how-to/cloud-servers/basic-types-of-linux-users-and-how-to-check-them/Picture1.png
  content/how-to/cloud-servers/basic-types-of-linux-users-and-how-to-check-them/index.md
Labels: new

#929 Create basic-types-of-linux-users-and-how-to-check-them
  content/how-to/cloud-servers/basic-types-of-linux-users-and-how-to-check-them/index.md
Labels: blocked, new

#911 Create get-the-database-size-in-mysql
  content/how-to/cloud-servers/get-the-database-size-in-mysql/index.md
Labels: new, review: peer

#910 Create install-and-configure-ftp-and-sftp-using-filezilla
  content/how-to/cloud-servers/install-and-configure-ftp-and-sftp-by-using-filezilla/index.md
Labels: new, review: peer

#927 Create remote-desktop-services-sessions-are-not-kept-alive
  content/how-to/cloud-servers/remote-desktop-services-sessions-are-not-kept-alive/index.md
Labels: new, review: peer

#914 Create updating-openssl-on-ubuntu
  content/how-to/cloud-servers/update-openssl-on-ubuntu/index.md
Labels: new, review: peer

#915 Create block-ip-range-from-countries-with-geoip-and-iptables
  content/how-to/cloud-servers/block-ip-range-from-countries-with-geoip-and-iptables/index.md
Labels: new, review: peer

#916 Create mysql-event-scheduler
  content/how-to/cloud-servers/mysql-event-scheduler/index.md
Labels: new, review: peer

#917 Create pitchfork-flavor-id-quickstart
  content/how-to/cloud-servers/pitchfork-flavor-id-quickstart/index.md
Labels: new, review: peer

#919 Create manually-granting-rdp-access-to-an-active-directory-user
  content/how-to/cloud-servers/manually-granting-rdp-access-to-an-active-directory-user/index.md
Labels: new, review: peer

#920 Create pitchfork-create-servers
  content/how-to/cloud-servers/pitchfork-create-servers/index.md
Labels: new, review: peer

#940 sin2 migration
  content/how-to/general/sin2-data-center-relocation-colocation-customer-faq/index.md
  content/how-to/general/sin2-data-center-relocation-managed-customer-faq/index.md
Labels: new

#925 Create how-to-resolve-MySQL-service-starting-and-stopping-unexpectedly/
  content/how-to/cloud-servers/how-to-resolve-mysql-service-starting-and-stopping-unexpectedly/index.md
Labels: new

#930 Create check-what-version-of-wordpress-is-being-used
  content/how-to/cloud-servers/check-the-version-of-wordpress-in-use/index.md
Labels: new

#922 Create using-pitchfork-for-cloud-images
  content/how-to/pitchfork-for-cloud-images/index.md
Labels: new, review: peer

#923 Create using-pitchfork-to-list-networks
  content/how-to/cloud-networks/use-pitchfork-to-list-networks/index.md
Labels: new, review: peer

#924 Create new article - Wordpress FTP
  content/how-to/cloud-servers/troubleshoot-wordpress-refusing-an-ftp-connection/index.md
Labels: new, review: peer

#950 Audit article: Manage user spam settings, changes per SME
  content/how-to/rackspace-email/rackspace-webmail-chat-faq/index.md
Labels: review: peer

#926 Create completing-a-csr-in-iis
  content/how-to/cloud-servers/complete-a-csr-in-iis/index.md
Labels: new

#918 Create configure-always-on-mssql-server-failover-clusters
  content/how-to/cloud-servers/configure-always-on-mssql-server-failover-clusters/index.md
Labels: new

#921 Create mysql-user-and-database-basics
  content/how-to/cloud-servers/mysql-user-and-database-basics/index.md
Labels: new, review: peer

#931 Create basic-linux-directory-permissions-and-how-to-check-them
  content/how-to/cloud-servers/basic-linux-directory-permissions-and-how-to-check-them/index.md
Labels: new

#958 Audit article: Why choose Cloud files?
  content/how-to/cloud-files/why-choose-cloud-files/index.md
Labels: full audit

#953 audit-email-blocklist
  content/how-to/rackspace-email/edit-blocklists-per-domain/index.md
Labels: full audit, review: peer

#955 audit-email-globalrights
  content/how-to/rackspace-email/set-global-access-rights-with-the-cloud-office-control-panel/index.md
Labels: full audit, review: peer

#956 audit-email-archived
  content/how-to/rackspace-email-archiving/import-and-export-archived-data/index.md
Labels: full audit, review: peer

#954 retire-email-outlook2011
  content/how-to/retired-articles/migrating-from-a-pop-server-to-rackspace-email-imap-using-outlook-2011-mac/2013-11-25_1013copy_0.jpg
  content/how-to/retired-articles/migrating-from-a-pop-server-to-rackspace-email-imap-using-outlook-2011-mac/Delete.png
  content/how-to/retired-articles/migrating-from-a-pop-server-to-rackspace-email-imap-using-outlook-2011-mac/Export_Shot_Mac.png
  content/how-to/retired-articles/migrating-from-a-pop-server-to-rackspace-email-imap-using-outlook-2011-mac/Import.png
  content/how-to/retired-articles/migrating-from-a-pop-server-to-rackspace-email-imap-using-outlook-2011-mac/Import_2copy.jpg
  content/how-to/retired-articles/migrating-from-a-pop-server-to-rackspace-email-imap-using-outlook-2011-mac/Location_filecopy.jpg
  content/how-to/retired-articles/migrating-from-a-pop-server-to-rackspace-email-imap-using-outlook-2011-mac/index.md
  static/_redirects
Labels: retired, review: peer

#962 Audit article: Getting started with CloudFiles, update RX Dev guide link
  content/how-to/cloud-files/getting-started-with-cloud-files-and-cdn/index.md
Labels: review: peer
