Repository rackerlabs/support-how-to, pull requests merged in 2021-01, with the labels that each got.

#772 correction on line 33
  content/how-to/cloud-backup/update-or-install-the-cloud-backup-agent-on-linux/index.md
Labels: review: peer

#773 Change file name to match permalink
  content/how-to/cloud-servers/migrations-in-the-rackspace-cloud/index.md
Labels: review: peer

#783 Create migrating-rds-cals
  content/how-to/cloud-servers/migrate-rds-cals/index.md
Labels: new

#786 Audit article: CentOS 7 Apache and PHP install
  content/how-to/cloud-servers/centos-7-apache-and-php-install/index.md
Labels: review: peer

#793 retire redirect aiops article
  content/how-to/retired-articles/aiops-alert-monitoring/RNS-Notifications.jpg
  content/how-to/retired-articles/aiops-alert-monitoring/index.md
  content/how-to/retired-articles/aiops-alert-monitoring/situation-ticket-example-1.png
  content/how-to/retired-articles/aiops-alert-monitoring/situation-ticket-text.png
  static/_redirects
Labels: retired

#797 Update index.md
  content/how-to/rackspace-email-archiving/export-an-archive-when-cancelling-your-account/index.md
Labels: review: peer

#796 Create setup-mail-Office365-Generic-Android-Application.md
  content/how-to/office-365/set-up-mail-Office365-Generic-Android-Application/index.md
Labels: new, review: peer

#795 Create Android-Gmail-Setup-Office365.md
  content/how-to/office-365/android-gmail-setup-office365/index.md
Labels: new

#802 updated date for relocation
  content/how-to/general/lon7-global-switch-data-center-migration-faq-for-managed-customers/index.md
Labels: review: peer

#803 Merge three redundant articles per Shaun Crumpler's request
  content/how-to/cloud-servers/shut-down-a-cloud-server/index.md
  content/how-to/cloud-servers/shut-down-a-rackspace-cloud-server/index.md
Labels: review: peer

#810 Redirect one of the broken links in Cloud Portal
  static/_redirects
Labels: review: peer

#815 Fix broken Cloud Portal links
  static/_redirects
Labels: review: editor

#817 Retire "Shut down a server article", it's redundant
  content/how-to/retired-articles/shut-down-a-server/index.md
Labels: review: editor

#818 Retire "Shut down a server from the Cloud portal" article, it's redundant.
  content/how-to/retired-articles/shut-down-a-server-from-the-cloud-portal/index.md
Labels: review: editor

#819 Retire Accessing Rackspace services through Vyatta
  content/how-to/retired-articles/a-quick-start-guide-to-launching-the-brocade-vyatta-vrouter/index.md
  content/how-to/retired-articles/accessing-rackspace-services-via-isolated-networks-through-the-vyatta-network-appliance/Vyatta.jpg
  content/how-to/retired-articles/accessing-rackspace-services-via-isolated-networks-through-the-vyatta-network-appliance/index.md
  static/_redirects
Labels: review: editor
