Repository rackerlabs/support-how-to, pull requests merged in 2021-05, with the labels that each got.

#1051 Audit article: rdp-connection-failures-expired-self-signed... new article
  content/how-to/cloud-servers/rdp-connection-failures-expired-self-signed-certificate/index.md
Labels: new

#1056 Reting article: Install Mongrel.... part 1
  content/how-to/cloud-servers/install-mongrel-and-mongrel-clusters-on-the-ubuntu-operating-system/index.md
  static/_redirects
Labels: review: editor

#1059 Retire old mfa
  content/how-to/retired-articles/myrackspace-multi-factor-authentication/index.md
  static/_redirects
Labels: retired, review: peer

#1021 Create new article
  content/how-to/cloud-servers/rdp-connection-failures-expired-self-signed-certificate/index.md
Labels: new

#1060 mfa updates 2
  content/how-to/cloud-servers/multi-factor-authentication-from-the-cloud-control-panel/index.md
  content/how-to/cloud-servers/multi-factor-authentication-from-the-myrackspace-portal/index.md
  content/how-to/cloud-servers/multifactor-authentication-from-the-cloud-control-panel/index.md
  content/how-to/cloud-servers/multifactor-authentication-from-the-cloud-control-panel/mfa-force-logout.png
  content/how-to/cloud-servers/multifactor-authentication-from-the-myrackspace-portal/index.md
  content/how-to/getting-started-with-hosted-email/index.md
  content/how-to/getting-started-with-office-365/index.md
  content/how-to/getting-started-with-public-cloud/index.md
  content/how-to/rackspace-intelligence/getting-started-with-rackspace-intelligence-for-the-cloud/index.md
  content/how-to/retired-articles/logging-in-to-the-rackspace-intelligence-dashboard/index.md
  content/how-to/retired-articles/myrackspace-multifactor-authentication/index.md
  static/_redirects
Labels: dependencies, review: peer

#1070 Audit article: elliptic-curve-operations, no changes
  content/how-to/cloud-servers/elliptic-curve-operations/index.md
Labels: full audit

#1065 Retire GlusterFS high availability part 1 and 2
  content/how-to/cloud-servers/glusterfs-high-availability-through-ctdb/index.md
  content/how-to/retired-articles/simple-load-balancing-with-apache/index.md
  static/_redirects
Labels: retired

#1071 Audit article: configura-apache-for-ssl...-load-balancer, no changes
  content/how-to/cloud-servers/configure-apache-for-ssl-termination-on-a-cloud-load-balancer/index.md
Labels: full audit, new

#1066 Audit article: Getting started with RBAC....changes per SME
  content/how-to/account-management/getting-started-with-role-based-access-control-rbac/index.md
Labels: full audit

#1077 Audit article: setting-up-a-mail-relay, no changes
  content/how-to/cloud-servers/set-up-a-mail-relay/index.md
  content/how-to/cloud-servers/setting-up-a-mail-relay/index.md
Labels: full audit

#1068 Create new article for Windows networking
  content/how-to/account-management/use-pivot-tables-with-your-cloud-billing-invoice/.rackspace_billing_new_excel_pivot_tables_demo.mov.icloud
  content/how-to/account-management/use-pivot-tables-with-your-cloud-billing-invoice/.rackspace_billing_open_office_pivot_tables_demo.mov.icloud
  content/how-to/cloud-servers/troubleshoot-windows-server-networking-issues/index.md
Labels: new, review: peer

#1081 retire vmware category
  CONTRIBUTING.md
  content/how-to/_index.md
  content/how-to/retired-articles/rpc-vmware-all-articles/index.md
  content/how-to/retired-articles/rpc-vmware-faq/index.md
  content/how-to/retired-articles/rpc-vmware/_index.md
  layouts/partials/components/support-docs.html
  static/_redirects
Labels: retired, review: editor

#1083 Cloud networks faq
  content/how-to/cloud-networks/cloud-networks-faq/index.md
  content/how-to/cloud-servers/common-windows-issues-why-password-resets-fail-on-a-domain-controller/index.md
Labels: review: peer

#1085 Create new article for accessing Cloud Files
  content/how-to/cloud-files/access-cloud-files-with-transmit/index.md
Labels: new

#1096 Fix bogus audit dates and correct script comments
  content/how-to/cloud-block-storage/troubleshoot-a-cloud-block-storage-volume-in-read-only-mode/index.md
  content/how-to/cloud-servers/complete-a-csr-in-iis/index.md
  content/how-to/cloud-servers/install-python-novaclient-on-windows/index.md
  content/how-to/cloud-servers/prepare-to-migrate-a-linux-server/index.html
  content/how-to/cloud-servers/resize-standard-and-general-purpose-servers/index.html
  script/audits.py
  script/no-audits.py
Labels: bug

#1098 Retire vyatta
  content/how-to/retired-articles/assemble-rackspace-email-webmail-and-outlook-web-access-owa-login-widget/ftrnavnarrow520x70.png
  content/how-to/retired-articles/assemble-rackspace-email-webmail-and-outlook-web-access-owa-login-widget/ftrnavwide820x50.png
  content/how-to/retired-articles/assemble-rackspace-email-webmail-and-outlook-web-access-owa-login-widget/index.md
  content/how-to/retired-articles/assemble-rackspace-email-webmail-and-outlook-web-access-owa-login-widget/stdshort320x150.png
  content/how-to/retired-articles/assemble-rackspace-email-webmail-and-outlook-web-access-owa-login-widget/stdtall350x210.png
  content/how-to/retired-articles/assemble-rackspace-email-webmail-and-outlook-web-access-owa-login-widget/vertshort200x220.png
  content/how-to/retired-articles/assemble-rackspace-email-webmail-and-outlook-web-access-owa-login-widget/verttall200x290.png
  content/how-to/retired-articles/brocade-vyatta-vrouter-supported-actions-through-the-cloud-control-panel/1555-3480-1.png
  content/how-to/retired-articles/brocade-vyatta-vrouter-supported-actions-through-the-cloud-control-panel/index.md
  content/how-to/retired-articles/configure-a-site-to-site-vpn-using-the-vyatta-network-appliance/SitetoSiteVPN_0.png
  content/how-to/retired-articles/configure-a-site-to-site-vpn-using-the-vyatta-network-appliance/index.md
  content/how-to/retired-articles/enable-internet-access-on-cloud-servers-using-snat-on-a-vyatta-network-appliance/FirewallFrontendingWebApp.png
  content/how-to/retired-articles/enable-internet-access-on-cloud-servers-using-snat-on-a-vyatta-network-appliance/index.md
  content/how-to/retired-articles/setting-up-vyatta-vpn-with-policy-nat/index.md
Labels: retired, review: peer

#1097 Add Ubuntu 16.04 to EoL/EoS list
  content/how-to/cloud-servers/hidden-base-images/index.md
Labels: review: peer

#1105 Audit article: Mount a partition and chroot into your primary file system from rescue mode, link changed
  content/how-to/cloud-servers/mount-a-partition-and-chroot-into-your-primary-file-system-from-rescue-mode/index.md
Labels: full audit

#1107 Mfa edits2
  content/how-to/cloud-servers/multifactor-authentication-from-the-cloud-control-panel/index.md
  content/how-to/cloud-servers/multifactor-authentication-from-the-myrackspace-portal/index.md
  static/_redirects
Labels: review: peer

#1110 Audit files: set-up-an-imap-account-on-a-windows-phone, folder name changed
  content/how-to/rackspace-email/set-up-an-imap-account-on-a-windows-phone/index.md
  content/how-to/rackspace-email/setting-up-an-imap-account-on-a-windows-phone/1.jpg
  content/how-to/rackspace-email/setting-up-an-imap-account-on-a-windows-phone/2.jpg
  content/how-to/rackspace-email/setting-up-an-imap-account-on-a-windows-phone/3.jpg
  content/how-to/rackspace-email/setting-up-an-imap-account-on-a-windows-phone/4.jpg
  content/how-to/rackspace-email/setting-up-an-imap-account-on-a-windows-phone/5.jpg
  content/how-to/rackspace-email/setting-up-an-imap-account-on-a-windows-phone/6.jpg
  content/how-to/rackspace-email/setting-up-an-imap-account-on-a-windows-phone/8.jpg
  content/how-to/rackspace-email/setting-up-an-imap-account-on-a-windows-phone/9.jpg
  content/how-to/rackspace-email/setting-up-an-imap-account-on-a-windows-phone/index.md
Labels: full audit

#1112 Audit files: cloud-feeds-faq, named hrefs in the accordions
  content/how-to/cloud-servers/cloud-feeds-faq/index.md
Labels: full audit

#1111 Audit article: help-tool-for-hosted-email-and-skype-for-business, lin…
  content/how-to/rackspace-email/help-tool-for-hosted-email-and-skype-for-business/index.md
Labels: full audit

#1113 Audit file: scheduled-images-faq, removes references to novaclient, u…
  content/how-to/cloud-servers/scheduled-images-faq/index.md
Labels: full audit

#1122 Audit file: managed-cloud-service-levels-faq, adds accordion
  content/how-to/managed-operations/managed-cloud-service-levels-faq/index.md
Labels: full audit

#1131 retire article: manage-ssh-key-pairs-for-cloud-servers-with-python-no…
  content/how-to/retired-articles/manage-ssh-key-pairs-for-cloud-servers-with-python-novaclient/index.md
  static/_redirects
Labels: retired

#1129 Retire article: Using python...part 1
  content/how-to/retired-articles/using-python-novaclient-to-manage-scheduled-images/index.md
  static/_redirects
Labels: full audit

#1127 Audit article: Introduction to encripted...no changes per SME
  content/how-to/cloud-servers/introduction-to-encrypted-authenticated-tokens/index.md
Labels: full audit, review: peer

#1126 Audit article: Disable HTTP compression...no changes per SME
  content/how-to/cloud-servers/disable-http-compression-in-apache/index.md
Labels: full audit, review: peer

#1125 Audit article: Updating password...no changes per SME
  content/how-to/rackspace-email/updating-password-authentication-method-on-your-ios-device/010.jpg
  content/how-to/rackspace-email/updating-password-authentication-method-on-your-ios-device/011.jpg
  content/how-to/rackspace-email/updating-password-authentication-method-on-your-ios-device/1_0.jpg
  content/how-to/rackspace-email/updating-password-authentication-method-on-your-ios-device/2_0.jpg
  content/how-to/rackspace-email/updating-password-authentication-method-on-your-ios-device/3_0.jpg
  content/how-to/rackspace-email/updating-password-authentication-method-on-your-ios-device/4_0.jpg
  content/how-to/rackspace-email/updating-password-authentication-method-on-your-ios-device/5_0.jpg
  content/how-to/rackspace-email/updating-password-authentication-method-on-your-ios-device/7_0.jpg
  content/how-to/rackspace-email/updating-password-authentication-method-on-your-ios-device/8-revised.jpg
  content/how-to/rackspace-email/updating-password-authentication-method-on-your-ios-device/9_0.jpg
  content/how-to/rackspace-email/updating-password-authentication-method-on-your-ios-device/index.md
Labels: full audit, review: peer

#1124 Audit article: Delete DNS Records, no changes per SME
  content/how-to/dedicated-hosting/manage-dns-records-in-the-myrackspace-portal/index.md
Labels: full audit, review: peer

#1123 Audit article: Speed up Rsync..no changes per SME
  content/how-to/cloud-servers/speed-up-rsync-when-migrating-a-linux-server-from-the-command-line/index.md
Labels: full audit, review: peer

#1115 Create new article - Sophos error on EOL Windows server
  content/how-to/cloud-servers/sophos-error-on-EOL-Windows-Server-2008/index.md
Labels: new

#1116 Create new article - Power off VM
  content/how-to/dedicated-hosting/power-off-a-VM-in-myrackspace-portal/index.md
Labels: full audit, new, review: peer

#1134 Slow windows logins
  content/how-to/cloud-servers/slow-windows-login/index.md
Labels: full audit, new, review: peer

#1133 Pr/csilva235/1119
  content/how-to/cloud-servers/basic-network-troubleshooting-with-powershell/index.md
Labels: full audit, new, review: peer

#1103 Create new article - Check Database corruption
  content/how-to/cloud-servers/check-database-for-corruption/index.md
Labels: new, review: peer

#1102 Create new article - Domain redirect types
  content/how-to/domain-redirect-types/index.md
Labels: new, review: peer

#1101 Create new article - Enable SSL and remote connections for MySQL
  content/how-to/cloud-servers/enable-SSL-and-remote-connections-for-mysql/index.md
Labels: new, review: peer

#1120 Create new article - Investigate Compromised Windows Server
  content/how-to/cloud-servers/investigate-a-compromised-windows-server/index.md
Labels: full audit, new, review: peer

#1143 Audit articles: nested-imap-folders-in-apple-mail,
  content/how-to/rackspace-email/nested-imap-folders-in-apple-mail/2_1.jpg
  content/how-to/rackspace-email/nested-imap-folders-in-apple-mail/3_2.jpg
  content/how-to/rackspace-email/nested-imap-folders-in-apple-mail/4_39.png
  content/how-to/rackspace-email/nested-imap-folders-in-apple-mail/Library.jpg
  content/how-to/rackspace-email/nested-imap-folders-in-apple-mail/Nestedcopy.jpg
  content/how-to/rackspace-email/nested-imap-folders-in-apple-mail/index.md
Labels: full audit

#1128 Audit article: Cloud Files FAQ, no changes per SME
  content/how-to/cloud-files/cloud-files-faq/index.md
Labels: full audit

#1117 Create new article - Checking Windows Updates
  content/how-to/cloud-servers/check-for-windows-updates-in-windows-server-2016-and-2019/index.md
Labels: new, review: peer

#1140 Audit files: upload-files-as-ascii-or-binary, name changes
  content/how-to/cloud-servers/should-i-upload-files-as-ascii-or-binary/index.md
  content/how-to/cloud-servers/upload-files-as-ascii-or-binary-with-ftp/index.md
Labels: full audit

#1147 Modify article, delete reference to RHEL/CentOS6 per SME
  content/how-to/cloud-servers/upgrade-apache-http-server-2.2-to-2.4-in-rhel-and-centos/index.md
Labels: full audit

#1144 Audit articles: create-a-sudo-user-in-ubuntu, no changes
  content/how-to/cloud-servers/create-a-sudo-user-in-ubuntu/index.md
Labels: full audit

#1145 Audit files: cloud-files-streaming-simple-flash-files, adds Disclaimer
  content/how-to/cloud-files/cloud-files-streaming-simple-flash-files/index.md
  content/how-to/cloud-files/stream-simple-flash-files-from-cloud-files/index.md
Labels: full audit

#1130 Audit article: Rackspace Neutron based..changes per SME
  content/how-to/cloud-networks/rackspace-neutron-based-networking-api-faq/index.md
Labels: full audit

#1132 Audit article: attach-a-cloud-network, change per SME
  content/how-to/cloud-networks/attach-a-cloud-network-to-an-existing-cloud-server/index.md
Labels: full audit

#1139 Audit files: rackspace-cloud-essentials-checking-a-server-s-ssh-host-…
  content/how-to/cloud-servers/rackspace-cloud-essentials-check-the-ssh-host-fingerprint-of-a-server-with-the-web-console/index.md
  content/how-to/cloud-servers/rackspace-cloud-essentials-checking-a-server-s-ssh-host-fingerprint-with-the-web-console/index.md
  static/_redirects
Labels: full audit

#1148 Audit article: prevent-issues-with-windows-server-reboots, takes out …
  content/how-to/cloud-servers/prevent-issues-with-windows-server-reboots/index.md
Labels: full audit

#1149 Audit files: streaming-cloud-files-with-jw-player, adds Disclaimer
  content/how-to/cloud-files/streaming-cloud-files-with-jw-player/index.md
Labels: full audit

#1135 Audit new article from: Pr/csilva235/1121
  content/how-to/cloud-servers/disable-third-party-applications-with-a-clean-boot-in-windows/index.md
Labels: full audit, new

#1100 Create new article - Perfect Forward Secrecy
  content/how-to/cloud-servers/how-to-enable-SSL-TLS-perfect-forward-secrecy/index.md
Labels: full audit, new

#1154 Audit file: cloud-files-streaming-simple-flash-files, updates static/…
  static/_redirects
Labels: full audit

#1146 Audit files: cloud-files-streaming-with-osmf-plugins, adds Disclaimer
  content/how-to/cloud-files/cloud-files-streaming-with-osmf-plugins/index.md
Labels: full audit

#1153 Retired article: manage-ssh-key-pairs-for-cloud-servers-with-python-n…
  static/_redirects
Labels: retired
