Repository rackerlabs/support-how-to, pull requests merged in 2021-06, with the labels that each got.

#1114 Create new article - TLS registry settings
  content/how-to/cloud-servers/transport-layer-security-registry-settings/index.md
Labels: new, review: peer

#1152 audit-record-types
  content/how-to/cloud-dns/choosing-dns-record-types/index.md
Labels: full audit, review: peer

#1155 phone-replacement
  content/how-to/account-management/billing-services-overview/index.md
  content/how-to/cloud-servers/cloud-servers-faq/index.md
  content/how-to/general/support/index.md
  content/how-to/rms-cloudflare/rms-cloudflare-faq/index.md
Labels: review: peer

#1156 Audit files: content/how-to/cloud-servers/about-cloud-server-images/i…
  content/how-to/cloud-servers/about-cloud-server-images/index.md
Labels: full audit

#1157 Audit article: rackspace-intelligence, removes 404 link
  content/how-to/rackspace-intelligence/_index.md
Labels: full audit

#1158 Audit file: updating-password-authentication-method-on-mac-mail, name…
  content/how-to/rackspace-email/update-password-authentication-method-on-mac-mail/index.md
  content/how-to/rackspace-email/updating-password-authentication-method-on-mac-mail/1_49.png
  content/how-to/rackspace-email/updating-password-authentication-method-on-mac-mail/2_46.png
  content/how-to/rackspace-email/updating-password-authentication-method-on-mac-mail/3_44.png
  content/how-to/rackspace-email/updating-password-authentication-method-on-mac-mail/4_37.png
  content/how-to/rackspace-email/updating-password-authentication-method-on-mac-mail/index.md
  static/_redirects
Labels: full audit

#1159 Audit how-to: set-up-rackspace-email-with-thunderbird,
  content/how-to/rackspace-email/set-up-rackspace-email-with-thunderbird/index.md
  content/how-to/rackspace-email/set-up-rackspace-email-with-thunderbird/thunderbird-create-account.png
  content/how-to/rackspace-email/set-up-rackspace-email-with-thunderbird/thunderbird-dialog-fields.png
Labels: full audit

#1160 Audit article: rackspace-cloud-dns-api-example, no changes
  content/how-to/cloud-dns/rackspace-cloud-dns-api-example/index.md
Labels: full audit, review: peer

#1151 audit-wordpress-user
  content/how-to/cloud-servers/add-a-new-wordpress-user/index.md
Labels: full audit, review: peer

#1161 Retires article: getting-started-with-apache-hadoop-on-rackspace-cloud
  content/how-to/retired-articles/getting-started-with-apache-hadoop-on-rackspace-cloud/index.md
  static/_redirects
Labels: retired

#1162 audit-dns-control
  content/how-to/cloud-dns/create-mx-records-for-google-apps-through-the-cloud-control-panel/addrecord.png
  content/how-to/cloud-dns/create-mx-records-for-google-apps-through-the-cloud-control-panel/index.md
  content/how-to/cloud-dns/creating-mx-records-for-google-apps-through-the-cloud-control-panel/index.md
Labels: full audit, review: peer

#1163 audit-dns-recordtypes
  content/how-to/cloud-dns/rackspace-cloud-dns-additional-resources/index.md
Labels: full audit, review: peer

#1165 audit-preparing-disk
  content/how-to/cloud-servers/prepare-data-disks-on-windows-2012-2016-and-2019-cloud-servers/index.md
  content/how-to/cloud-servers/preparing-data-disks-on-windows-cloud-servers/index.md
Labels: full audit, review: peer

#1167 number-update
  content/how-to/general/support/index.md
Labels: review: peer

#1168 command rectification
  content/how-to/cloud-servers/prevent-issues-with-windows-server-reboots/index.md
Labels: review: peer

#1169 asia-number-update
  content/how-to/general/support/index.md
Labels: review: peer

#1172 Audit changes legal, Rackspace changes to Rackspace Technology
  content/how-to/general/legal/index.md
Labels: full audit

#1175 Audit article: using-ssl-with-your-cloud-database-instance:
  content/how-to/cloud-databases/use-ssl-with-your-cloud-database-instance/index.md
  static/_redirects
Labels: full audit

#1176 Matrix table correction
  content/how-to/dedicated-hosting/ngfw-feature-matrix/index.md
Labels: review: peer

#1184 audit-dmarc
  content/how-to/rackspace-email/create-a-dmarc-policy/index.md
Labels: full audit, review: peer

#1183 audit-dns-defs
  content/how-to/rackspace-email/dns-record-definitions/index.md
Labels: full audit, review: peer

#1182 audit-skype-devguide
  content/how-to/skype-for-business/hosted-microsoft-skype-for-business-at-rackspace-deployment-guide/index.md
Labels: full audit, review: peer

#1179 Create new article - SSH keep alive
  content/how-to/cloud-servers/how-to-keep-ssh-sesions-alive/index.md
Labels: new, review: peer

#1178 Create New Article - Troubleshoot Wordpress Internal Server Error
  content/how-to/cloud-servers/troubleshoot-wordpress-internal-server-error/index.md
Labels: new, review: peer

#1190 new file: File size upload in nginx
  content/how-to/cloud-servers/limit-file-upload-size-in-nginx/index.md
Labels: new

#1192 Audit article: choosing-between-rdbms-and-nosql, no changes
  content/how-to/managed-operations/choosing-between-rdbms-and-nosql/index.md
Labels: full audit

#1194 Audit article: examples-of-rdbms-and-nosql-databases, updates databas…
  content/how-to/managed-operations/examples-of-rdbms-and-nosql-databases/index.md
Labels: full audit

#1187 audit-outlook-import
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-windows/advanced2016.png
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-windows/browse_import2016.png
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-windows/export2016.png
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-windows/import_from2016.png
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-windows/import_from_a_file2016.png
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-windows/index.md
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-windows/options2016.png
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-windows/outlook_data_file.png
Labels: full audit, review: peer

#1185 audit-spf
  content/how-to/rackspace-email/create-an-spf-policy/index.md
Labels: full audit, review: peer

#1189 audit-email-ios
  content/how-to/rackspace-email/configure-a-renamed-email-address-for-iphone-ios/index.md
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-iphone-iOS/imap-serversettings.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-iphone-iOS/index.md
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-iphone-iOS/mapping-folderlist.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-iphone-iOS/mapping-ontheserver.png
  content/how-to/rackspace-email/rename-a-rackspace-email-address-overview/index.md
Labels: full audit, review: peer

#1188 audit-email-ts
  content/how-to/rackspace-email/troubleshoot-email-delivery/index.md
Labels: full audit, review: peer

#1191 audit-safelist
  content/how-to/rackspace-email/safelist-addresses-domains-and-ips-in-rackspace-email/index.md
Labels: full audit, review: peer

#1195 audit-bp-mail
  content/how-to/rackspace-email/best-practices-for-sending-emails-to-many-recipients/index.md
Labels: full audit, review: peer

#1197 audit-email-spoofing
  content/how-to/rackspace-email/email-spoofing-best-practices/index.md
Labels: full audit, review: peer

#1186 audit-outlook2016
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-windows/advanced2016.png
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-windows/browse_finish2016.png
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-windows/export2016.png
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-windows/export_folder_list2016.png
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-windows/export_to_file2016.png
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-windows/index.md
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-windows/options2016.png
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-windows/outlook_data_file2016.png
Labels: full audit, review: peer

#1204 Audit files: using-python-novaclient-with-the-rackspace-cloud, update…
  content/how-to/cloud-servers/using-python-novaclient-with-the-rackspace-cloud/index.md
Labels: full audit

#1203 Audit articles: introduction-to-cassandra, no changes
  content/how-to/managed-operations/introduction-to-cassandra/index.md
Labels: full audit

#1202 Audit article: intro-to-databases-intro, no changes
  content/how-to/managed-operations/intro-to-databases-intro/index.md
Labels: full audit

#1201 Audit file: introduction-to-mongodb, adds registered trademarks
  content/how-to/managed-operations/introduction-to-mongodb/index.md
Labels: full audit

#1200 Audit article: reasons-to-use-an-sql-database, fixes broken link
  content/how-to/managed-operations/reasons-to-use-an-sql-database/index.md
Labels: full audit

#1199 Audit article: reasons-to-use-a-nosql-database, no changes
  content/how-to/managed-operations/reasons-to-use-a-nosql-database/index.md
Labels: full audit

#1196 Audit article: types-of-databases, no changes
  content/how-to/managed-operations/types-of-databases/index.md
Labels: full audit

#1198 audit article: properties-of-rdbmss-and-nosql-databases, fixes broken…
  content/how-to/managed-operations/properties-of-rdbmss-and-nosql-databases/index.md
Labels: full audit

#1206 audit-email-storage
  content/how-to/rackspace-email/rackspace-email-storage-maintenance-and-best-practices/RSEstorageNotificationsSC1.png
  content/how-to/rackspace-email/rackspace-email-storage-maintenance-and-best-practices/index.md
Labels: full audit, review: peer

#1205 audit-imap-folders
  content/how-to/rackspace-email/synchronize-imap-folders-for-new-accounts-in-apple-mail/IMAP_MailboxBehaviors.png
  content/how-to/rackspace-email/synchronize-imap-folders-for-new-accounts-in-apple-mail/IMAP_SentFolderMapping.png
  content/how-to/rackspace-email/synchronize-imap-folders-for-new-accounts-in-apple-mail/IMAP_SpamFolderMapping.png
  content/how-to/rackspace-email/synchronize-imap-folders-for-new-accounts-in-apple-mail/IMAP_TrashFolderMapping.png
  content/how-to/rackspace-email/synchronize-imap-folders-for-new-accounts-in-apple-mail/el_capitan_yosemite_FolderMapping_Sent.png
  content/how-to/rackspace-email/synchronize-imap-folders-for-new-accounts-in-apple-mail/el_capitan_yosemite_MailboxFolderList.png
  content/how-to/rackspace-email/synchronize-imap-folders-for-new-accounts-in-apple-mail/index.md
  content/how-to/rackspace-email/synchronize-imap-folders-for-new-accounts-in-apple-mail/preference-mapping-sierra.png
Labels: full audit, review: peer

#1209 Audit webmail
  content/how-to/rackspace-email/configure-a-renamed-email-address-for-iphone-ios/imap-serversettings.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-for-iphone-ios/index.md
  content/how-to/rackspace-email/configure-a-renamed-email-address-for-iphone-ios/mapping-folderlist.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-for-iphone-ios/mapping-ontheserver.png
  content/how-to/rackspace-email/rackspace-webmail/index.md
Labels: full audit, review: peer

#1208 Audit files: useful-python-novaclient-commands, publishes article again and updates…
  content/how-to/cloud-servers/useful-python-novaclient-commands/index.md
  content/how-to/retired-articles/useful-python-novaclient-commands/index.md
  static/_redirects
Labels: full audit

#1218 update the tutorials
  CONTRIBUTING.md
Labels: review: peer
