Repository rackerlabs/support-how-to, pull requests merged in 2021-02, with the labels that each got.

#822 Updates previous articles per SME's request. SME provided the changes
  content/how-to/rackspace-email/adding-an-alias-with-rackspace-email/index.md
Labels: review: peer

#823 Audit article: Creating and deleting local users on Windows
  content/how-to/cloud-servers/creating-and-deleting-local-users-on-windows-server/index.md
Labels: review: peer

#828 retire vyatta articles
  content/how-to/cloud-networks/brocade-vyatta-vrouter-supported-actions-through-the-cloud-control-panel/index.md
  content/how-to/cloud-networks/configure-a-site-to-site-vpn-using-the-vyatta-network-appliance/index.md
  content/how-to/cloud-networks/enable-internet-access-on-cloud-servers-using-snat-on-a-vyatta-network-appliance/index.md
  content/how-to/cloud-servers/setting-up-vyatta-vpn-with-policy-nat/index.md
  content/how-to/retired-articles/a-quick-start-guide-to-launching-the-brocade-vyatta-vrouter/index.md
  content/how-to/retired-articles/brocade-vyatta-vrouter-configuration-guide/index.md
  content/how-to/retired-articles/brocade-vyatta-vrouter-faq/index.md
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/MACAuthenticationSettings.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/MACConnectionDetails.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/MACNetworkPrefs.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/MACSplitTunnell.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/MACSuccessfulConnection.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/VPNwithVyatta.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/WinConnecttoaNetwork_0.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/WinSplitTunneling.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/WinTheconnectionisready.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/WinTypetheinternetaddresstoconnectto.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/WinUsernameandPassword.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/WinVyattaAdvancedProperites.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/WinVyattaVPNProperties.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/WinVyattaVPNSecurityTab.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/WindowsSetUpVPN.png
  content/how-to/retired-articles/configure-remote-access-vpn-service-on-a-vyatta-appliance/index.md
  content/how-to/retired-articles/creating-nat-rules-for-vyatta-vrouter/883-1_0.png
  content/how-to/retired-articles/creating-nat-rules-for-vyatta-vrouter/index.md
  content/how-to/retired-articles/vyatta-eol-faq/index.md
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-1.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-10_0.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-11_1.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-12_0.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-13.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-2_0.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-3_1.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-4_0.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-5_0.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-6_0.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-7_0.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/884-8_0.png
  content/how-to/retired-articles/vyatta-ipsec-site-to-site-vpn/index.md
  content/how-to/retired-articles/vyatta-snmp-and-logging/index.md
  content/how-to/retired-articles/vyatta-vrouter-add-a-local-administrative-user/880-1_0.png
  content/how-to/retired-articles/vyatta-vrouter-add-a-local-administrative-user/880-2.png
  content/how-to/retired-articles/vyatta-vrouter-add-a-local-administrative-user/index.md
  content/how-to/retired-articles/vyatta-vrouter-allow-an-ip-address-to-access-the-vrouter-via-ssh/index.md
  content/how-to/retired-articles/vyatta-vrouter-configure-an-interface-firewall/index.md
  static/_redirects
Labels: retired, review: peer

#794 Create dfs-replication-installation
  content/how-to/cloud-servers/dfs-replication-installation/index.md
Labels: new

#829 audit-name-renewal
  content/how-to/rackspace-email/domain-name-renewal/index.md
Labels: full audit, review: peer

#833 Retire article: Outlook sync err, as outlook 2010 no longer supported
  content/how-to/retired-articles/fix-outlook-synchronization-errors/1_55.png
  content/how-to/retired-articles/fix-outlook-synchronization-errors/2_52.png
  content/how-to/retired-articles/fix-outlook-synchronization-errors/3a.png
  content/how-to/retired-articles/fix-outlook-synchronization-errors/index.md
  static/_redirects
Labels: review: editor

#845 CBU-967 primary user bug
  content/how-to/cloud-backup/cloud-backup-faq/index.md
  content/how-to/cloud-backup/update-or-install-the-cloud-backup-agent-on-linux/index.md
Labels: review: peer

#844 audit-email-plus
  content/how-to/rackspace-email/rackspace-email-plus-getting-started/index.md
  content/how-to/rackspace-email/rackspace-email-plus-getting-started/screenshot_01.png
Labels: full audit, review: peer

#843 audit-email-phonecollection
  content/how-to/rackspace-email/enable-and-disable-collection-of-mobile-phone-numbers-in-rackspace-webmail/index.md
Labels: full audit, review: peer

#842 audit-email-imap
  content/how-to/rackspace-email/migrating-from-a-pop-server-to-rackspace-email-imap-using-outlook/index.md
Labels: full audit, review: peer

#840 audit-cbs-impact
  content/how-to/cloud-block-storage/minimizing-the-impact-of-cloud-block-storage-maintenance/index.md
Labels: full audit, review: peer

#839 audit-cbs-matrix
  content/how-to/cloud-block-storage/permissions-matrix-for-cloud-block-storage/index.md
Labels: full audit, review: peer

#838 audit-cbs-prepare
  content/how-to/cloud-block-storage/prepare-your-cloud-block-storage-volume/index.md
Labels: full audit, review: peer

#850 audit-cbs-clone
  content/how-to/cloud-block-storage/create-a-clone-of-a-cloud-block-storage-volume/index.md
  content/how-to/cloud-block-storage/create-and-attach-a-cloud-block-storage-volume/index.md
Labels: full audit, review: peer

#856 Create plesk-introduction
  content/how-to/cloud-servers/plesk-introduction/index.md
Labels: new

#858 Create plesk-ssl-installation
  content/how-to/cloud-servers/plesk-ssl-installation/index.md
Labels: new

#854 Create mounting-cloud-files-with-cloudfuse
  content/how-to/cloud-servers/mounting-cloud-files-with-cloudfuse/index.md
Labels: new

#859 Update to string
  content/how-to/cloud-servers/plesk-introduction/index.md
Labels: new

#860 Update from SecureShell
  content/how-to/cloud-servers/plesk-ssl-installation/index.md
Labels: new

#862 retire-cbs-onmetal
  content/how-to/retired-articles/attach-a-cloud-block-storage-volume-to-an-onmetal-server/index.md
  static/_redirects
Labels: retired, review: peer

#853 Create mysql-connection-methods
  content/how-to/cloud-servers/mysql-connection-methods/index.md
Labels: new, review: peer

#861 retire-ip-lockdown
  content/how-to/retired-articles/locking-down-ip-addresses-in-migrationwiz/Step_1.png
  content/how-to/retired-articles/locking-down-ip-addresses-in-migrationwiz/Step_3.png
  content/how-to/retired-articles/locking-down-ip-addresses-in-migrationwiz/Step_4.png
  content/how-to/retired-articles/locking-down-ip-addresses-in-migrationwiz/Step_5.png
  content/how-to/retired-articles/locking-down-ip-addresses-in-migrationwiz/advanced.png
  content/how-to/retired-articles/locking-down-ip-addresses-in-migrationwiz/index.md
  static/_redirects
Labels: retired, review: peer

#855 create reasonable endeavors article
  content/how-to/account-management/reasonable-endeavors-billable-services-for-linux/index.md
Labels: new, review: sme or author

#864 audit-cbs-overview
  content/how-to/cloud-block-storage/cloud-block-storage-overview/index.md
Labels: full audit, review: peer

#863 audit-cbs-detach
  content/how-to/cloud-block-storage/detach-and-delete-cloud-block-storage-volumes/index.md
Labels: full audit, review: peer

#857 plesk-managing-email-accounts
  content/how-to/cloud-servers/plesk-manage-email-accounts/index.md
Labels: new, review: peer

#869 audit-cbs-mount
  content/how-to/cloud-block-storage/cloud-block-storage-attaching-vs-mounting/index.md
Labels: full audit, review: peer

#868 audit-email-tools
  content/how-to/rackspace-email/cloud-office-migrations-faq/index.md
  content/how-to/rackspace-email/email-domain-tools-cloud-office-control-panel/index.md
  content/how-to/rackspace-email/set-an-email-catch-all-address/index.md
  content/how-to/rackspace-email/split-domain-routing/index.md
Labels: full audit, review: peer

#870 audit-cbs-faq
  content/how-to/cloud-block-storage/cloud-block-storage-faq/index.md
Labels: full audit, review: peer

#873 Audit article: Run additional passes with MigrationWiz
  content/how-to/rackspace-email/run-additional-passes-with-migrationwiz/index.md
  content/how-to/rackspace-email/run-additional-passes-with-migrationwiz/picture1.png
  content/how-to/rackspace-email/running-additional-passes-with-migrationwiz/2013-12-04_1555copy.jpg
  content/how-to/rackspace-email/running-additional-passes-with-migrationwiz/index.md
Labels: review: peer

#872 audit-intel-suppressions
  content/how-to/rackspace-intelligence/getting-started-with-rackspace-intelligence-for-the-cloud/index.md
  content/how-to/rackspace-intelligence/monitoring-entities-with-rackspace-intelligence/index.md
  content/how-to/rackspace-intelligence/monitoring-open-alerts-with-rackspace-intelligence/index.md
  content/how-to/rackspace-intelligence/understanding-the-rackspace-intelligence-dashboard-user-interface/index.md
  content/how-to/rackspace-intelligence/work-with-notification-suppressions-in-rackspace-intelligence/index.md
Labels: full audit, review: peer

#874 audit-intel-diff
  content/how-to/rackspace-intelligence/differences-between-rackspace-intelligence-for-cloud-account-and-dedicated-account/index.md
Labels: full audit, review: peer

#875 audit-intel-graphs
  content/how-to/rackspace-intelligence/create-custom-graphs-of-activity-in-rackspace-intelligence/4743.1a.png
  content/how-to/rackspace-intelligence/create-custom-graphs-of-activity-in-rackspace-intelligence/4743.2a.png
  content/how-to/rackspace-intelligence/create-custom-graphs-of-activity-in-rackspace-intelligence/index.md
  content/how-to/rackspace-intelligence/creating-custom-graphs-of-activity-in-rackspace-intelligence/index.md
Labels: full audit, review: peer

#879 add how-to products
  CONTRIBUTING.md
Labels: review: peer

#880 add product name
  CONTRIBUTING.md
Labels: review: peer

#883 broken link
  content/how-to/rackspace-email/migrate-your-email-by-using-the-self-service-migration-tool/index.md
Labels: review: peer

#881 audit-intel-dashboard
  content/how-to/rackspace-intelligence/understanding-the-rackspace-intelligence-dashboard-user-interface/index.md
Labels: full audit, review: peer

#882 audit-intel-setup
  content/how-to/rackspace-intelligence/set-up-a-server-to-work-with-rackspace-intelligence/index.md
Labels: full audit, review: peer

#891 audit-intel-logs
  content/how-to/rackspace-intelligence/examining-the-log-of-alerts-suppressed-by-rackspace-intelligence/index.md
Labels: full audit, review: peer

#892 audit-intel-preparing
  content/how-to/rackspace-intelligence/preparing-to-use-rackspace-intelligence/index.md
Labels: full audit, review: peer

#886 audit-intel-faq
  content/how-to/rackspace-intelligence/rackspace-intelligence-faq/index.md
Labels: full audit, review: peer

#893 audit-intel-notifications
  content/how-to/rackspace-intelligence/working-with-notifications-in-rackspace-intelligence/index.md
Labels: full audit

#885 audit-intel-database-setup
  content/how-to/rackspace-intelligence/setting-up-a-database-to-work-with-rackspace-intelligence/index.md
Labels: full audit, review: peer

#884 audit-intel-interface
  content/how-to/rackspace-intelligence/understanding-the-rackspace-intelligence-user-interface-for-dedicated-accounts/index.md
Labels: full audit, review: peer
