Repository rackerlabs/support-how-to, pull requests merged in 2021-07, with the labels that each got.

#1213 Manage ssh key pairs for cloud servers with python novaclient
  content/how-to/cloud-servers/manage-ssh-key-pairs-for-cloud-servers-with-python-novaclient/index.md
  content/how-to/retired-articles/manage-ssh-key-pairs-for-cloud-servers-with-python-novaclient/index.md
  static/_redirects
Labels: full audit

#1228 Toosalgado18project 1
  content/how-to/dedicated-hosting/how-to-request-a-csr/CSR1.png
  content/how-to/dedicated-hosting/how-to-request-a-csr/CSR2.png
  content/how-to/dedicated-hosting/how-to-request-a-csr/index.md
  content/how-to/dedicated-hosting/request-for-additional-ips/Subject.png
Labels: new

#1227 Toosalgadopatch1: using-sftp-and-scp
  content/how-to/cloud-servers/use-sftp-and-scp/index.md
Labels: new

#1231 apply fixes
  content/how-to/dedicated-hosting/add-cpu-to-server-or-hypervisor/index.md
  content/how-to/dedicated-hosting/add-disk-space-to-server-or-hypervisor/index.md
  content/how-to/dedicated-hosting/add-new-vpn-user-myrackspace-portal/index.md
  content/how-to/dedicated-hosting/add-ram-to-server-or-hypervisor/index.md
  content/how-to/dedicated-hosting/check-bandwidth-usage/index.md
  content/how-to/dedicated-hosting/create-new-user-on-active-directory-domain/index.md
  content/how-to/dedicated-hosting/delete-an-object-group-with-firewall-manager-v2/index.md
  content/how-to/dedicated-hosting/delete-vpn-user-myrackspace-portal/index.md
  content/how-to/dedicated-hosting/firewall-manager-v2/index.md
  content/how-to/dedicated-hosting/how-to-request-a-csr/index.md
  content/how-to/dedicated-hosting/id-federation-map-policies-permissions-dedicated/index.md
  content/how-to/dedicated-hosting/manage-local-users-in-the-myrackspace-portal/index.md
  content/how-to/dedicated-hosting/manage-user-permissions-for-dedicated-hosting/index.md
  content/how-to/dedicated-hosting/modify-an-object-group-with-firewall-manager-v2/index.md
  content/how-to/dedicated-hosting/request-additional-ip-addresses/index.md
  content/how-to/dedicated-hosting/reset-user-password-on-active-directory-domain/index.md
  content/how-to/dedicated-hosting/reset-your-cisco-asa-vpn-user-password-by-using-the-rackspace-portal/index.md
  content/how-to/dedicated-hosting/view-an-object-group-with-firewall-manager-v2/index.md
  content/how-to/dedicated-hosting/view-your-network-device-configuration/index.md
Labels: review: peer

#1212 [WIP] Aws marketplace
  content/how-to/_index.md
  content/how-to/rackspace-services-for-aws/_index.md
  content/how-to/rackspace-services-for-aws/rackspace-government-cloud-secure-configuration-baseline/index.md
  content/how-to/rackspace-services-for-aws/rackspace-services-for-aws-all-articles/index.md
  content/how-to/rackspace-services-for-aws/rackspace-services-for-aws-faq/index.md
  content/how-to/rackspace-services-for-aws/secure-configuration-baseline-launch-instructions/advanced-details.png
  content/how-to/rackspace-services-for-aws/secure-configuration-baseline-launch-instructions/index.md
  content/how-to/rackspace-services-for-aws/secure-configuration-baseline-launch-instructions/instance-details.png
  content/how-to/rackspace-services-for-aws/secure-configuration-baseline-launch-instructions/rgs-ami-confirm-screen.png
Labels: review: peer

#1232 add content for ms vulnerability
  content/how-to/general/remediation-of-cve-2021-34527-windows-print-spooler-remote-code-execution-vulnerability/index.md
Labels: review: peer

#1220 audit-import-export
  content/how-to/rackspace-email/import-or-export-contacts-in-rackspace-email/ExportContactsRSE.png
  content/how-to/rackspace-email/import-or-export-contacts-in-rackspace-email/ImportContactsRSE1.png
  content/how-to/rackspace-email/import-or-export-contacts-in-rackspace-email/ImportContactsRSE2.png
  content/how-to/rackspace-email/import-or-export-contacts-in-rackspace-email/index.md
Labels: full audit, review: peer

#1219 audit-applemail
  content/how-to/rackspace-email/configure-a-renamed-email-address-in-apple-mail/accounttype_imap.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-in-apple-mail/imap_serversettings.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-in-apple-mail/index.md
  content/how-to/rackspace-email/configure-a-renamed-email-address-in-apple-mail/mail_addaccountdropdown.png
Labels: full audit, review: peer

#1216 Create new article - too many connection in mysql
  content/how-to/cloud-servers/too-many-connections-error-in-mysql/index.md
Labels: new, review: peer

#1226 retire-fawsRDS
  content/how-to/retired-articles/access-a-private-rds-instance-with-putty/index.md
  static/_redirects
Labels: full audit, review: peer

#1225 audit-load-testing
  content/how-to/cloud-servers/application-and-load-testing-guidelines/index.md
Labels: full audit, review: peer

#1224 audit-blocked
  content/how-to/rackspace-email/cloud-office-blocked-attachment-files/index.md
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-mac/file_import2016.png
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-mac/import_file_type2016.png
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-mac/import_finish2016.png
  content/how-to/rackspace-email/import-email-address-data-into-outlook-2016-for-mac/index.md
Labels: full audit, review: peer

#1223 audit-spam
  content/how-to/rackspace-email/spam-filtering/index.md
Labels: full audit, review: peer

#1222 audit-ts-failed-email
  content/how-to/rackspace-email/troubleshoot-failed-email-connection/index.md
Labels: full audit, review: peer

#1233 audit-email-renamed
  content/how-to/rackspace-email/rename-a-rackspace-email-address/edit-mailbox-options.png
  content/how-to/rackspace-email/rename-a-rackspace-email-address/index.md
  content/how-to/rackspace-email/rename-a-rackspace-email-address/rename-pop-up-SC1.png
  content/how-to/rackspace-email/rename-a-rackspace-email-address/success-message.png
Labels: full audit, review: peer

#1247 audit-email-plus
  content/how-to/rackspace-email/upgrade-to-rackspace-email-plus/RSE-Plus.png
  content/how-to/rackspace-email/upgrade-to-rackspace-email-plus/index.md
Labels: full audit, review: peer

#1246 audit-delete-mailbox
  content/how-to/rackspace-email/delete-a-rackspace-email-mailbox/add-mailbox-sc1.png
  content/how-to/rackspace-email/delete-a-rackspace-email-mailbox/click_username.png
  content/how-to/rackspace-email/delete-a-rackspace-email-mailbox/delete-rse-box-sc2.png
  content/how-to/rackspace-email/delete-a-rackspace-email-mailbox/delete_button.png
  content/how-to/rackspace-email/delete-a-rackspace-email-mailbox/delete_mult_mailboxes.png
  content/how-to/rackspace-email/delete-a-rackspace-email-mailbox/index.md
  content/how-to/rackspace-email/delete-a-rackspace-email-mailbox/yes_delete.png
Labels: full audit, review: peer

#1245 audit-outlook-win
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-outlook-for-windows/OL16windowsSC1.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-outlook-for-windows/OL16windowsSC2.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-outlook-for-windows/OL16windowsSC3.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-outlook-for-windows/OL16windowsSC4.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-outlook-for-windows/OL16windowsSC5.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-outlook-for-windows/OL16windowsSC6.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-outlook-for-windows/OL16windowsSC7.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-outlook-for-windows/OL16windowsSC8.png
  content/how-to/rackspace-email/configure-a-renamed-email-address-on-outlook-for-windows/index.md
Labels: full audit, review: peer

#1248 Updated article, and fixed 404 link per Z McCroklyn's request
  content/how-to/managed-operations/adding-a-managed-operations-service-level-to-your-cloud-account/index.md
Labels: review: peer

#1252 Fix some syntax errors
  content/how-to/cloud-images/pitchfork-for-cloud-images/index.md
Labels: review: sme or author

#1253 date meta
  content/how-to/cloud-images/pitchfork-for-cloud-images/index.md
Labels: review: peer

#1251 audit-ts-sql
  content/how-to/cloud-servers/troubleshoot-remote-access-to-sql-server/index.md
Labels: full audit, review: peer

#1250 audit-export2016
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-mac/file_export2016.png
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-mac/index.md
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-mac/items_exported2016.png
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-mac/macOS-Export.png
  content/how-to/rackspace-email/export-email-address-data-from-outlook-2016-for-mac/save_as2016.png
Labels: full audit, review: peer

#1257 Update index.md
  content/how-to/retired-articles/RETIRING-CONTENT/index.md
Labels: review: peer

#1256 Retire Install and configure RXT Monitoring agent per Steph
  content/how-to/retired-articles/RETIRING-CONTENT/install-and-configure-the-rackspace-monitoring-agent/index.md
  static/_redirects
Labels: review: peer

#1258 What is the cloud and its products
  content/how-to/general/the-cloud-and-its-products/cdn.png
  content/how-to/general/the-cloud-and-its-products/cloud.gif
  content/how-to/general/the-cloud-and-its-products/index.md
Labels: review: peer

#1261 edits per Tom
  content/how-to/general/sjc2-data-center-relocation-colocation-customer-faq/index.md
Labels: review: peer

#1244 Article - DNS API calls with Pitchfork
  content/how-to/cloud-dns/dns-api-calls-with-pitchfork/index.md
Labels: new, review: peer

#1243 Article - VPN Tunnel Creation Request
  content/how-to/dedicated-hosting/vpn-tunnel-creation-request/index.md
Labels: new, review: peer

#1259 audit article: vhosts-basics, adds changes requested by the author
  content/how-to/cloud-servers/vhost-basics/vhost-and-server-blocks-basics/index.md
  content/how-to/cloud-servers/vhosts-basics/index.md
Labels: full audit

#1240 Article - grep basics
  content/how-to/cloud-servers/grep-basics/index.md
Labels: new
