Repository rackerlabs/support-how-to, pull requests merged in 2021-04, with the labels that each got.

#960 audit-email-protection
  content/how-to/rackspace-email/rackspace-email-protection-from-external-images-in-webmail/index.md
Labels: full audit, review: peer

#965 Create New Article - Nginx Redirects
  content/how-to/cloud-servers/create-redirects-in-nginx/index.md
Labels: new, review: peer

#966 Create new article for indoes in Linux
  content/how-to/cloud-servers/what-are-inodes-in-linux/index.md
Labels: new, review: peer

#969 audit-server-blockip
  content/how-to/cloud-servers/block-an-ip-address-on-a-windows-server/index.md
Labels: full audit, review: peer

#968 audit-servers-realse
  content/how-to/cloud-servers/rackspace-product-release-phases/index.md
Labels: full audit, review: peer

#970 audit-server-solution
  content/how-to/cloud-servers/the-hosting-spectrum-which-solution-fits-your-business/index.md
Labels: full audit, review: peer

#975 Audit article: Use Swiftly to upload an image, freshened up links per SME
  content/how-to/cloud-files/use-swiftly-to-upload-an-image/index.md
Labels: review: peer

#977 Audit article: Set up a static website
  content/how-to/cloud-files/set-up-a-static-website-with-cloud-files/index.md
  content/how-to/cloud-files/use-swift-to-manage-large-files/index.md
Labels: review: peer

#976 Audit article: Use Swift to manage large files, no changes per SME
  content/how-to/cloud-files/use-swift-to-manage-large-files/index.md
Labels: review: peer

#980 Audit article: Use the API to..., no changes per SME
  content/how-to/cloud-files/use-the-api-to-manage-large-files/index.md
Labels: review: peer

#971 Create article - install wordpress multisite
  content/how-to/cloud-servers/install-wordpress-multisite/index.md
Labels: new

#982 Author suggestions
  content/how-to/cloud-servers/mysql-user-and-database-basics/index.md
Labels: review: sme or author

#972 Create article - install apache on Debian 10.
  content/how-to/cloud-servers/install-apache-on-debian-10/index.md
Labels: new, review: peer

#988 SME suggestion
  content/how-to/cloud-servers/mysql-user-and-database-basics/index.md
Labels: review: sme or author

#989 edits and outdated link correction
  content/how-to/cloud-servers/common-windows-issues-key-management-server-activation/index.md
Labels: review: peer

#993 Create article for installing wordpress in centos 7
  content/how-to/cloud-servers/install-wordpress-in-centos-7/index.md
Labels: new

#994 Audit article: Use annotation metrics. Change title, no changes per SME
  content/how-to/rackspace-metrics/use-annotation-metrics/index.md
Labels: full audit

#1000 SME suggestion
  content/how-to/cloud-servers/mysql-user-and-database-basics/index.md
Labels: review: peer

#991 create new article for adding wordpress users
  content/how-to/cloud-servers/add-a-new-wordpress-user/index.md
Labels: new, review: peer

#1015 retiring eol articles
  content/how-to/retired-articles/adding-disk-space-after-resizing-a-windows-2003-cloud-server/Win2003FormatPartition.png
  content/how-to/retired-articles/adding-disk-space-after-resizing-a-windows-2003-cloud-server/Win2003NewPartition.png
  content/how-to/retired-articles/adding-disk-space-after-resizing-a-windows-2003-cloud-server/index.md
  content/how-to/retired-articles/creating-an-outbound-port-deny-rule-for-windows-firewall-windows-2008/index.md
  content/how-to/retired-articles/install-pyrax/index.md
  content/how-to/retired-articles/lon5-cloud-migration-faq/index.md
  content/how-to/retired-articles/useful-python-novaclient-commands/index.md
  content/how-to/retired-articles/vnc-install/index.md
  static/_redirects
Labels: retired

#1014 merging into main account management faq
  content/how-to/account-management/account-management-faq/index.md
  content/how-to/cloud-servers/what-happens-if-i-do-not-supply-a-vat-id-number/index.md
  static/_redirects
Labels: full audit, review: peer

#1016 audit-nginx
  content/how-to/cloud-servers/install-nginx-on-fedora/index.md
Labels: full audit, review: peer

#1018 audit-netapp
  content/how-to/cloud-servers/migrating-a-net-application-from-amazon-web-services/index.md
Labels: full audit, review: peer

#1013 create-site-seal-code
  content/how-to/general/add-a-site-seal-code-to-your-website/index.md
  content/how-to/general/add-a-site-seal-code-to-your-website/site-seal-code.jpg
Labels: new, review: peer

#992 Create new article for using fail2ban
  content/how-to/cloud-servers/using-fail2ban/index.md
Labels: new

#1026 Change permalink, file name and create redirect
  content/how-to/cloud-networks/attach-and-detach-networks-from-a-cloud-server/index.md
  static/_redirects
Labels: review: editor

#1019 Create new article
  content/how-to/cloud-servers/troubleshooting-sql-log-shipping/index.md
Labels: new, review: peer

#1024 Update Email Archive Data export limit per Clint Fellows
  content/how-to/rackspace-email-archiving/rackspace-email-archiving-faq/index.md
Labels: review: peer

#1030 reformatting and edits for audit
  content/how-to/cloud-servers/linux-out-of-memory-killer/index.md
Labels: full audit, review: peer

#1031 Audit article: basic-network-troubleshooting, no changes
  content/how-to/cloud-networks/basic-network-troubleshooting/index.md
Labels: review: peer

#1020 Create new article
  content/how-to/cloud-servers/set-windows-defender-folder-exclusions/index.md
Labels: new, review: peer

#1033 remove duplicate file and move article to correct product folder
  content/how-to/cloud-images/pitchfork-for-cloud-images/index.md
  content/how-to/cloud-servers/dfs-replication-installation/index.md
  content/how-to/cloud-servers/pitchfork-for-cloud-images/index.md
Labels: review: peer

#1036 fix malformed tables
  content/how-to/office-365/o365-spheres-of-support/index.md
Labels: review: peer

#1037 Audit server flavor
  content/how-to/cloud-servers/how-to-choose-your-cloud-server-flavor/index.md
  content/how-to/general/site-seal-code/index.md
  content/how-to/general/site-seal-code/site-seal-code.jpg
Labels: review: peer

#984 first revision with Bryan
  content/how-to/cloud-servers/multi-factor-authentication-from-the-cloud-control-panel/index.md
Labels: review: peer
